### ISSUE TITLE
Chrome node is not opening the browser localized anymore

### ISSUE THREAD

**Issue by corisima** [SeleniumHQ/docker-selenium#1009]
## 💥 Regression Report

In the past, when using selenium/node-chrome, I was able to open a localized Chrome (e.g. in Spanish language). 

Now, the browser always opens in English.

Last working version: selenium/node-chrome:3.141.59-zinc

Stopped working in version: latest release 3.141.59-zirconium

## To Reproduce

1. Use the latest selenium/node-chrome (version 3.141.59-zirconium):

docker run --name selenium-node-chrome-1 -d --network test-net -e HUB_HOST=selenium-hub -e HUB_PORT=4444 -e REMOTE_HOST=http://selenium-node-chrome-1:5555 -e SCREEN_WIDTH=2560 -e SCREEN_HEIGHT=1600 -v "$PWD":/data -v /dev/shm:/dev/shm selenium/node-chrome:3.141.59-zinc

2. Create the Chrome RemoteWebDriver with a language different from English:

 ChromeOptions options = new ChromeOptions();
 ...
 options.addArguments("lang=es");
 DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability(ChromeOptions.CAPABILITY, options);
 ...
 WebDriver driver = new RemoteWebDriver(getHubUrl(hostname), capabilities);         

3. Open a website which detects the language & displays the pages in that language. A good example is https://www.whatsmybrowser.org/ (if the browser's language is Spanish, this website would display the page in Spanish etc)

driver.get(" https://www.whatsmybrowser.org/");

4. Look at this pages, notice what language they are displayed in

## Expected behavior

The browser to open locallized (in Spanish, in this example).

## Actual behavior

The browser always opens in English.

**Comment by diemol** [comment]
Hi @corisima,
What happens if you try that with your local Chrome installation?

**Comment by omkarnathsingh** [comment]
Tried on local machine, looks like its node selenium issue. Google has changed the behavior :(

**Comment by corisima** [comment]
Yup, it works ok with local Chrome.

**Comment by reinholdfuereder** [comment]
We stumbled over this problem as well:
* In the past (Chrome/ChromeDriver version < 80, i.e. still with v79) with default Docker Selenium standalone Chrome node:
  * by default no language preference (Accept-Language request HTTP header; checked with PHP via: `$_SERVER['HTTP_ACCEPT_LANGUAGE']`) was set
  * with "goog:chromeOptions" Selenium capability (`--lang=fr-FR`) the language can be set => the result is "fr-FR" with this Codeception (PHP testing framework) configuration:
```
...
modules:
  enabled:
    - WebDriver:
        ...
        browser: chrome
        capabilities:
          "goog:chromeOptions":
            args: ["--headless", "--disable-gpu", '--lang=fr-FR']
            ...
```
* On my local Windows desktop (Chrome v80 -- v80.0.3987.116/v80.0.3987.132 -- with ChromeDriver v79 or v80):
  * by default use language preference "de", i.e. the one from my Windows system
  * with aforementioned "goog:chromeOptions" Selenium capability (`--lang=fr-FR`) the language can be set => the result is "fr" (not "fr-FR" though)!
* With default Docker Selenium standalone Chrome node ("selenium/standalone-chrome:3.141.59-zirconium")
  * by default use language preference "en-US", i.e. the one from underlying (Docker) Linux system
  * **with aforementioned "goog:chromeOptions" Selenium capability (`--lang=fr-FR`) the language can NOT be set anymore => the result keeps to be "en-US"!!!**

### Conclusions:
* Assuming that Chrome on purpose changed from using no language preference to the one from the underlying OS, I think forcing the language via "goog:chromeOptions" Selenium capability (via `--lang=...`) is seemingly broken for Chrome under Linux (but it still works under Windows), isn't it?
* And I also guess Docker Selenium Chrome Node Image is not to blame, or is it?
* Is there a Chrome bug report for that? Or should there be one? Or is my analysis incomplete/wrong?

**Comment by reinholdfuereder** [comment]
A small update -- in fact confirmation -- of my previous comment/suspicion (https://github.com/SeleniumHQ/docker-selenium/issues/1009#issuecomment-597662480):
* Background: Additional test with Selenium server and Chrome (v80.0.3987.122) and ChromeDriver (v80) running on a colleagues Linux laptop (i.e. without Docker Selenium Chrome Node)
* I thus claim the issue "_forcing the language via "goog:chromeOptions" Selenium capability (via --lang=...)_" is really "only" in Linux Chrome, and not specific to this Docker Selenium Chrome Node Image
  * (unless forcing the language must be done differently since v80)

=> Chrome bug report!?

**Comment by reinholdfuereder** [comment]
I have just found this old bug that sounds related: https://crbug.com/1010288
Although it is for Chrome v77, I could imagine that they have fixed it before (because in my tests it also seemed to work with v79) and re-broken it again for v80?

Any thoughts/ideas?
Should I try to file a new Chrome bug report?
(Now that Chrome development seems to delay new features -- and major Chrome version releases -- in favour of bug fixing there is new hope; especially, because this issue was not the only new problem experienced with Chrome/ChromeDriver v80/zirconium release)

**Comment by diemol** [comment]
Sorry for the late reply.

I just tried on my machine (OSX Catalina), and the same behavior you mentioned @reinholdfuereder, it does not work.

However, when using a Windows machine it does work. So it is definitely an issue under *nix environments. 

I'll be closing this since it is a Chrome issue, if someone reports it, feel free to put the link of the bug report here, thanks!

>Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by corinasima** [comment]
It looks like there's some activity on the aforementioned chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1010288 (it's open & assigned since March 2021), so hopefully a fix will follow sometime in the future.

Thanks!
