### ISSUE TITLE
Selenium Hub handles around 500 connections from chrome node pods then crashes with outofmemory

### ISSUE THREAD

**Issue by samueltauil** [SeleniumHQ/docker-selenium#1011]
## 🐛 Bug Report

I'm trying to deploy 600 chrome nodes (pods) and get them registered to a single Hub, but looks like when reaching ~500 connections the Hub crashes with out of memory for spining up new threads:

`2020-02-20 22:47:43.209:WARN:osjs.HttpChannel:qtp377478451-5453: /grid/register
java.lang.OutOfMemoryError: unable to create new native thread`

## To Reproduce

I'm following the steps here to deploy: 
https://github.com/kubernetes/examples/tree/master/staging/selenium

Then I scale up the chrome nodes up to 510.
I've made some changes to the supervisord config file and rebuilt the containers to check if that was the case but still got this limitation.
I've also configured the `-Xss228k` into a JAVA_OPTS variable and still got same results.
I tried to bump up the number of threads for Jetty adding the GRID_JETTY_MAX_THREADS variable to something like 700 or so but same results.

Here are some links to commits I did in my forked repo:
https://github.com/samueltauil/docker-selenium/commits?author=samueltauil

## Expected behavior

Get all the chrome nodes properly registered.

## Environment

OS: OpenShift 4.3 
Docker-Selenium image version: 3.141.59-zirconium

**Comment by samueltauil** [comment]
Just for the sake of better context here is the log snippet that shows exactly when it crashed, no matter how attributes are defined.

`16:52:03.691 INFO [DefaultGridRegistry.add] - Registered a node http://10.129.6.19:5555
16:52:03.692 INFO [DefaultGridRegistry.add] - Registered a node http://10.129.6.27:5555
16:52:03.693 INFO [DefaultGridRegistry.add] - Registered a node http://10.129.6.16:5555
Exception in thread "Thread-507" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at org.openqa.grid.selenium.proxy.DefaultRemoteProxy.startPolling(DefaultRemoteProxy.java:169)
	at org.openqa.grid.internal.DefaultGridRegistry.add(DefaultGridRegistry.java:340)
	at org.openqa.grid.web.servlet.RegistrationServlet.lambda$process$0(RegistrationServlet.java:109)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by diemol** [comment]
Apologies for the late reply.

I checked briefly the linked repos, and I don't see where the `JAVA_OPTS` env var is being overwritten, which is what is needed to increase the heap memory, and of course to have the pod with enough available memory.

You could have a look at the [helm chart](https://github.com/helm/charts/tree/master/stable/selenium) that is ready to use in Kubernetes, and it has the option already to overwrite the `JAVA_OPTS` env var.

I also think that using `-Xss228k` is not enough, please also have a look at the different options explained in this SO [answer](https://stackoverflow.com/questions/1565388/increase-heap-size-in-java).

I will close this since the options to increase the heap memory are there and available, if this is more a troubleshooting type of issue, we should treat it as a question, therefore:

>💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
>  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
>  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
>  * 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
