### ISSUE TITLE
Tag Docker image for 85.0.4183.87

### ISSUE THREAD

**Issue by radar** [SeleniumHQ/docker-selenium#1103]
## 🚀 Feature Proposal

Create a tag for image 85.0.4183.87. 

## Motivation

This version of Chromedriver fixes a regression: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578.

**Comment by radar** [comment]
I also noticed that the `latest` tag is not the same as the `85.0` tag. Is this intentional?

**Comment by diemol** [comment]
@radar this release includes that ChromeDriver version
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-alpha-7-prerelease-20200904

And yeah, `latest` points to the docker images for Selenium 3.x, it is intended since Grid 4 is still in alphas. Changing `latest` to point to the alphas could break a few things.
