### ISSUE TITLE
It seems that Selenium and the Browser's driver stucks after a while. 

### ISSUE THREAD

**Issue by Dimitvp** [SeleniumHQ/docker-selenium#1208]
## 💥 Regression Report
I am fairly new with Docker and Selenium.
I am sorry if this is not the right place for my problem but I don't know what to do anymore. Most probably it's not a problem with the version but something with my set up.
I am currently testing on:
Windows 10 Pro
My **Docker Linux Stacks** are:
     **.Net Core 3.1** App + **NordVPN** Container:3.7.4 + **standalone-chrome**: latest
I am starting 3 of this **Stacks**: 
     2 with selenium/standalone-**chrome** 
     1 with selenium/standalone-**firefox**
All of them get stuck at some point. Usually around the same time, few minutes from each other.
And the only fix is manually to restart the whole Stack:
`docker-compose down`
`docker-compose up`

I think the problem is with Selenium because it happens with Chrome and with Firefox. The VPN is working fine no errors or exceptions there.
I've tried with **separate** containers for Selenium hub and Chrome/Firefox Nodes, same behavior.
 
Sometimes this is the error:
`OpenQA.Selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED`
This is usually problem with the web page. I am fine with that.

But most of the times it is just stays at `Started new session` after 60 sec:
` The HTTP request to the remote WebDriver server for URL  http://localhost:4444/wd/hub timed out after 60 seconds.,`

![Screenshot_3](https://user-images.githubusercontent.com/7417488/107335012-1b58c680-6ac0-11eb-9b9d-c6ae7f9fd771.png)

I've read many issues around, including:
https://github.com/SeleniumHQ/docker-selenium/issues/79
https://github.com/SeleniumHQ/docker-selenium/issues/87
https://github.com/SeleniumHQ/docker-selenium/issues/89

I've tried all the suggestions, no luck.

## Expected behavior

The app is using the Chrome/Firefox/Selenium container from time to time, on random. The idea is just to open a web page 1-2 sec. and to close the page and the WebDrive.
Usually it works fine for some hours. **4 hours**, **5 hours**, the record is **25 hours**. But always it stuck at some point and I've to restart it manually. 
If it happens once per week I am ok with that but this is happening way too often.

## Environment

OS: Windows 10 Pro
Docker-Selenium image version: Latest
-->
Docker version: v20.10.2
Docker-Compose version (if applicable): 3.4
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
`version: '3.4'

**Comment by diemol** [comment]
@Dimitvp, not sure what the issue can be, there is no clear diagnostic from your side so I cannot say where the issue might be.

Why don't you join our Slack/IRC channel, where we all can have a look and give you hints on what is going wrong. Check the links here https://www.selenium.dev/support/

I also edited your initial post because you posted some user/password credentials.

**Comment by Dimitvp** [comment]
@diemol  "I also edited ...." Thank you for that. Really stupid of me. I missed it for some reason.
I will join the group but can you, please, give me more points on "no clear diagnostic"? It is not very clear to me **what** you mean by that. It is not very clear to me **how** to achieve that.
Selenium it's not giving me more logs then what i shared. 
I tried implementing `selenium/node-chrome-debug` + **VNC**, hoping I will see more information. But I am having all sorts of other problems there. One of them is that **VNC** cant connect to the Node at all. (I removed the **VPN** for that test because i will need **Nginx** if I want **VNC** to connect to the container from the outside world)
Maybe my problem is that i don`t know Linux and I have to do something in the Inside Docker Linux env so i can extract more information. 
And thank you for responding.

**Comment by diemol** [comment]
@Dimitvp, what I meant by that is that it is complicated for us to understand what the issue is. Narrative descriptions are normally not good for bug reports because they are full of assumptions, what is needed in a bug report is a clear way to reproduce the issue. 

When no clear way to reproduce the issue is provided, it could mean that there is an issue with the setup or any other problem out of the scope of Selenium, that is why I suggested to join our Slack/IRC channels, where we all can help in diagnosing and understanding the issue.
