### ISSUE TITLE
Selenium session capabilities should show the noVNC port that user has configured so that user can see the execution.

### ISSUE THREAD

**Issue by kiruparkuma** [SeleniumHQ/docker-selenium#1327]
## 🚀 Feature Proposal

I have setup the selenium 4 docker Grid with chrome nodes attached to it.
6 Different chrome nodes are added to Hub with ports 7900 to 7905 for noVNC.
When i do multiple runs on i am not able to locate on which port the execution is happening.
How to get the VNC port on which the Test execution is happening.

## Motivation

When multiple tests are executed on grid, its hard to find on which noVNC port the execution is happening.
## Example

Please provide an example for how this feature would be used.
When the tests get executed , selenium session capabilities could show the noVNC port that user has configured. so user can see the execution.

**Comment by diemol** [comment]
I forgot to reply to this issue mentioning that this was already possible since a while ago. Grid 4 when running in our Docker images has a live view working out of the box. To use this properly, the `SE_NODE_GRID_URL` needs to be set with the public Grid url (so to say, the url one can use to reach out to the Grid UI). This docker-compose [file](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml) is an example of that.

In the end, you do not need to know the url or port where the VNC stream is available as this is handled by the Grid UI for you.

Here is a video showing how it works

https://user-images.githubusercontent.com/5992658/134482481-bf9143bb-aec2-4727-a347-64239f730353.mov
