### ISSUE TITLE
Unable to execute any tests on chrome since 3.141.59-20210729 (CPU usage +400%)

### ISSUE THREAD

**Issue by lacell75** [SeleniumHQ/docker-selenium#1346]
## 🐛 Bug Report
Since the latest version with chrome 92.0 , I can't launch test on chrome node. The CPU usage has blow up.

## To Reproduce

Start a chrome node in docker and a selenium hub. Launch a test.

Please see below the graphana of machines : 
1- Before, the CPU usage was 0.4 CPU max :
![image](https://user-images.githubusercontent.com/33258660/127485941-adaa635b-c620-42bc-b39e-8bf81e87e8ea.png)

2- Now, the CPU usage is 1.8 CPU (x4) :
![image](https://user-images.githubusercontent.com/33258660/127486123-6ed98602-9b14-4d3d-8434-6b442533cada.png)

**Comment by diemol** [comment]
Yeah, seems Chrome is doing something strange there.

Could you please:
- submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
- try to set `--disable-gpu` in your capabilities? I read somewhere that it might help.

**Comment by lacell75** [comment]
Thanks with `--disable-gpu` that works now

**Comment by tom-cn** [comment]
+1

**Comment by tom-cn** [comment]
same here, change back to `3.141.59-20210713`, works now

**Comment by diemol** [comment]
`3.141.59-20210713` has Chrome 91.

So please report this issue to the Chrome team, as it seems not related to the Docker images.

**Comment by sparky005** [comment]
Hey @lacell75 if you opened an issue with the Chrome team do you mind posting the link here? We think we are experiencing a similar issue and would like to track.

**Comment by lacell75** [comment]
hi @sparky005 ,sorry i didn't have time to open it yet

**Comment by kiview** [comment]
Hey @lacell75 and @diemol,
I am currently investigating issues in https://github.com/testcontainers/testcontainers-java that seem to be related to this as well.

And indeed `--disable-gpu` helped for us as well.

@diemol 
Are you sure it is a good idea to close this issue? Updating the existing tags of the Docker image with a Chrome version that introduced a potential regression has an impact on downstream projects as well.

Of course, I am mostly interested in understanding and solving the root cause as well.

**Comment by diemol** [comment]
@kiview I have pinned this issue to the issues tab so folks can see it right away. 

I am not sure if reopening this would help because the root problem is probably related to Chrome itself. Would be nice if someone who is hitting this issue reports it to the Chrome team. 

We always run a few basic tests before every release, I confess the first run failed and the retry passed, so it was hard to detect this. Since there is a workaroung, `--disable-gpu`, we do not see the need to revert the release.

We clearly have no intention to break downstream projects. As I said above, we have a few sanity tests and they passed. However, please understand that we are covering many fronts with a small group of folks, most of them helping on their free time. Would be great to see help coming from downstream projects, and then we could potentially identify these issues earlier.

**Comment by phil-mitchell** [comment]
@diemol why not update the latest tag with a working version?  This has a huge impact on CI pipelines downstream and adding `--disable-gpu` is a big chore.  Clearly this is not a working image, despite having a workaround.  Leave the image with the most explicit version up there, but please revert the `latest` tag.

**Comment by kiview** [comment]
@diemol Sure, I don't want to criticize your release or test process in any way, I know how hard it is to maintain an OSS project with limited resources. I just wanted to encourage leaving this issue open for discoverability, without the issue and your proposed workaround, we would have had a very hard time debugging it. However, thanks to finding this, we were able to implement a fix quickly.

While I would like to report this issue further upstream with the Chrome team, I lack the understanding of the issue to report it sufficiently and I think it requires more investigation, to triage if this is a Docker specific issue (and I would not expect them to take responsibility of 3rd party distributions).

Besides, if you want to discuss how we can better support your release process (e.g. by our Testcontainers pipeline acting as a further smoke test for new images), I am open.

Edit:
As noted in the other issue, [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1228625) is the corresponding Chromium issue, thanks to whoever reported this.

**Comment by diemol** [comment]
> @diemol why not update the latest tag with a working version? This has a huge impact on CI pipelines downstream and adding `--disable-gpu` is a big chore. Clearly this is not a working image, despite having a workaround. Leave the image with the most explicit version up there, but please revert the `latest` tag.

I pushed a moment ago a new [release](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-20210804), which adds the `--disable-gpu` flag in the startup Chrome script, while the upstream bug is fixed. This makes the image usable.

In the long term, I think we should remove the tag `latest`, users are getting releases without noticing and they are not aware most of the time what browser they are testing on, which is not optimal. Ideally, one should be in control of the versions and tags used in the testing/release pipeline to avoid these surprises. 

@kiview, sure, an extra layer of testing would be good, what do you have in mind? Why don't you join our Slack/IRC channels and we chat more over there (links at https://www.selenium.dev/support/).

**Comment by phil-mitchell** [comment]
@diemol I agree in principle with the removal of the `latest` tag.  The one concern I have is that all modern browsers push updates to their customers anyway, so customers will effectively be using the `latest` tag while CI/CD pipelines will invariably test with something older.  This might slow down discovery of actual regressions due to browser updates.  That said, browser regression discovery should not impact ongoing bug fixing and feature development in PRs.  Removing the `latest` tag would force developers to come up with their own validation + tagging process to consume new images.  Seems fair.

Also thanks for pushing the workaround image as a short-term solution to my laziness.
