### ISSUE TITLE
[🚀 Feature]: Being able to use docker.sock instead of the tcp API with Dynamic Grid

### ISSUE THREAD

**Issue by maartenheebink** [SeleniumHQ/docker-selenium#1430]
### Feature and motivation

Debian uses nftables instead of iptables and Docker won't start when having daemon.json set to enable the tcp endpoint _out of the box_.

Would be nice to be able to use unix:///var/run/docker.sock, as that is out of the box mountable from host to container so Debian and Docker don't have to be modified.

### Usage example

People won't be needing to modify the Docker daemon, the workings of Debian and should be able to just put unix:///var/run/docker.sock in their config.toml instead of host.docker.internal or 172.17.0.1.

**Comment by maartenheebink** [comment]
@diemol, does the 'help wanted' tag require input or action from my side?

**Comment by diemol** [comment]
Means that this issue is looking for contributors.

**Comment by therealdjryan** [comment]
@maartenheebink,
Have you tried mounting /var/run/docker.sock on the nodes, possibly in combination with setting:

CONTAINER_HOST=unix://var/run/docker.sock?

**Comment by davyrod** [comment]
@therealdjryan I attempted your suggestion with no success as I am facing a similar issue.  I assume the 'url' entry in the config.toml overrides the docker.sock mount?

**Comment by maartenheebink** [comment]
> @maartenheebink, Have you tried mounting /var/run/docker.sock on the nodes, possibly in combination with setting:
> 
> CONTAINER_HOST=unix://var/run/docker.sock?

Thanks @therealdjryan, this works. I commented out the url in the config.toml and mapped the file to the container, didn't need to add CONTAINER_HOST. Only thing i had was permission issues, but fixed that on the host side.

Did i miss this in the documentation perhaps or should this be included? As i didn't find this info initially.

**Comment by diemol** [comment]
I think I tried once to mount `unix://var/run/docker.sock` but due to the permissions issue preferred to recommend the other way. However, I did not spend any time figuring out what to chance on the host to make it work. If you share the details, we'd be happy to document and even change the defaults!

**Comment by maartenheebink** [comment]
I got it starting for the first time having used 'chmod 777 /var/run/docker.sock' in the host but that shouldn't be the solution for production-grade environments.
Still working on a better solution right now.

**Comment by maartenheebink** [comment]
Finally had the chance to look at this again:

On my fresh install of Debian 11.
User ID: 1000
Docker group ID: 998

Added the docker.sock volume mapping to the docker-compose. As we already confirmed, this doesn't work because of permission issues.

In the node container i added a group called docker `$ groupadd docker` and changed its ID to 998 to match the host `$ groupmod -g 998 docker`. 
Then i added `seluser` to the `docker` group `$ groupadd -aG docker seluser`.
After a restart of the container the permission issues were gone.

Would like to propose that you can add a group-id to the composefile with the id of the docker group on the host so that on container creation the group is created and the id is set accordingly. [Linuxserver.io does this in their images as well. ](https://hub.docker.com/r/linuxserver/plex).

I figured out the ID's by running `$ id` on the host giving me the id of the docker group.

@diemol @therealdjryan

**Comment by ibodog** [comment]
I can replicate @maartenheebink steps and create a new docker image from the base image that will work on my system and use /var/run/docker.sock.  But am having a hard time getting a solution that works by configuring an environment variable to do the same steps at run time of the base image.  The GID of docker group is not guaranteed to be the same on every system so that needs to be able to change in the container to match the GID on the host at runtime.

Mostly seems due to issues in linux recognizing that the 'seluser' has been made a member of the 'docker' group without logging out and in again.  

I tried 'newgrp docker' command and variations, but in the container the script hangs on this line (I think waiting for password).  Supervisord doesn't seem to have a way to sequence startup of multiple scripts, so that is a hurdle, too, for the way this container works.  I tried logic in both start-selenium-grid-node-docker.sh script as well as defining a new supervisord application and having a separate script.

If there is a way to start a sub script from the first script as 'seluser' and have it pickup the group change it could all be done in start-selenium-grid-node-docker.sh script.  But I'm not finding a way to do that...

Linuxserver image referenced in comment above seems to be using some "cont-init" running as root to achieve adding the group before starting the user process.  https://github.com/linuxserver/docker-baseimage-ubuntu/tree/bionic/root/etc/cont-init.d

**Comment by ibodog** [comment]
OK, found a solution (on my ubuntu 20.04) that requires 2 scripts.  1st script adds the 'docker' group and then calls the normal start-selenium-grid-node-docker.sh script via 'sg' command.

add-docker-group.sh
```
#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e
echo "**** Creating 'docker' group and adding 'seluser' to it..."
sudo groupadd -g $GID_DOCKER docker
sudo usermod -aG docker seluser
sg - docker -c "/opt/bin/start-selenium-grid-node-docker.sh"
```
selenium-grid-node-docker.conf has to be modified to start this script instead.
`command=/opt/bin/add-docker-group.sh
`
And Dockerfile.txt has to add both .sh scripts to /opt/bin
```
COPY start-selenium-grid-node-docker.sh \
    config.toml \
    add-docker-group.sh \
    /opt/bin/
```

docker-compose file needs to add environment variable that matches the host's docker group GID and mount /var/run/docker.sock
```
Environment:
  - GID_DOCKER=998
Volumes:
  - /var/run/docker.sock:/var/run/docker.sock
```
 
And finally, in config.toml, remove any 'url =' lines by commenting them out 
`
\# url = "http://172.17.0.1:2375"
`

Run generate.sh, build a new local image, and start your docker-compose group.

Seems hacky...  Here's what the process tree looks like in the running container:
```
seluser@11ce18e20c3a:/$ ps x --forest
    PID TTY      STAT   TIME COMMAND
     28 ?        S      0:00 sh -c /opt/bin/start-selenium-grid-node-docker.sh
     29 ?        S      0:00  \_ bash /opt/bin/start-selenium-grid-node-docker.sh
     30 ?        Sl     0:04      \_ java -jar /opt/selenium/selenium-server.jar node --publish-events tcp://selenium-hub:4442 --subscribe-events tcp://seleniu
    104 pts/0    Ss     0:00 bash
    112 pts/0    R+     0:00  \_ ps x --forest
      1 ?        Ss     0:00 bash /opt/bin/entry_point.sh
      8 ?        S      0:00 /usr/bin/python3 /usr/bin/supervisord --configuration /etc/supervisord.conf
     10 ?        S      0:00  \_ bash /opt/bin/add-docker-group.sh
```

NOTE: I'm seeing some possibly timing related issues with this scheme.  Sometimes on 'docker-compose up -d' the node-docker fails.  But 'docker-compose up' or 'docker-compose up -d && docker-compose logs -f' usually results in a running grid...

**Comment by diemol** [comment]
All that can be probably implemented as an [entry_point](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Base/entry_point.sh) but only for the `NodeDocker` and the `StandaloneDocker`. 

Maybe we need to check if `sudo` is available before running those commands, sometimes folks like to use those images in environments where `sudo` is not avaialable. 

I could have a look at this at some point, but I'd be very happy to receive PRs for this.

**Comment by diemol** [comment]
One issue I've bumped into while giving this a try is that the approach described above is not working cross platform. Seems to work in Linux envs, but not in macOS. I have not tried Windows yet.
This [issue](https://github.com/docker/for-mac/issues/4755) is preventing it to work on macOS.

Probably we need to rethink and see if we can use a different approach.

**Comment by diemol** [comment]
#1505 is an attempt to implement this, using a workaround (sadly). The idea is to iterate and get feedback on this.

Works well on macOS, testing on Windows and Ubuntu. When the CI and tests on other platforms work, will merge.
