### ISSUE TITLE
Investigate RAM considerations in the Nodes

### ISSUE THREAD

**Issue by mtscout6** [SeleniumHQ/docker-selenium#15]
@c0nstructor Brought up a valid concern about RAM consumption when running a node that only drives a single browser session at a time. (See issue #14)
- [ ] Validate that this is a concern. (Provide some metrics)
- [ ] Is [restricting the JVM RAM](http://stackoverflow.com/questions/1493913/how-to-set-the-maximum-memory-usage-for-jvm) usage a viable option?
- [ ] What is the Docker stance on this?
- [ ] What is a happy default that will satisfy the community?

**Comment by rubytester** [comment]
We used to run 4 nodes per one VM and our issue ended up being a CPU maxing out, not memory. I have since dialed down a VM with 2 cpu to run 1 node but I increased to 2 browser sessions per node. We get about 80% max cpu utilization.  I start a node wit JAVA_OPTS=-Xmx4G since the VM has 6 G RAM. this seems a nice box to build grids. My standard grid is a hub on 1 VM and 20 nodes on 20 VM machines. Works for us.

**Comment by Julioevm** [comment]
I've been finding selenium using more and more ram inside the node containers ever since I moved from 3.11 to 3.14x version of the containers.
I'm currently using selenium/node-firefox:3.141.59-radium
with --privileged and --shm-size 2g parameters
Now they start at around 150Mbs but after several tests have run though these nodes the selenium ram usage keeps growing. 
I could run 15 nodes at once on a google cloud machine with 15 Gb of ram and now I had to lower it to 10 nodes and up the ram to 20 to prevent the machines from running out.
I re-create the containers after every test, but still some test have hundreds of executions and the ram usage, I believe, is too high. Could this be a memory leak? The driver sessions quit at the end of each execution.
Here are the selenium processes on a machine running some nodes inside containers.
![image](https://user-images.githubusercontent.com/38758281/60882446-30b4a180-a248-11e9-9407-8aae896918f6.png)
Here are the size of the selenium processes after a while:
![image](https://user-images.githubusercontent.com/38758281/60882499-5346ba80-a248-11e9-8a58-07d2223d1449.png)

**Comment by diemol** [comment]
@Julioevm is there a way that you can provide a scenario to reproduce that memory usage?

**Comment by Julioevm** [comment]
> @Julioevm is there a way that you can provide a scenario to reproduce that memory usage?

Ill try to set up an scenario to reproduce this.

**Comment by diemol** [comment]
I am going to close this as it has become stale.

If someone finds issues with this, please open a new issue with enough information.
