### ISSUE TITLE
Alpine Linux as base image

### ISSUE THREAD

**Issue by lcacciagioni** [SeleniumHQ/docker-selenium#161]
Guys how about using alpine linux as the base image? This can be a great enhancement in the reduction of the final size of the image.

**Comment by andrerom** [comment]
+1 This is only image I personally use that still pulls in ubuntu, so switching to jessie, or better yet jumping directly to alpine linux like others offical images are about to would be great to reduce build/test/download time for everyone.

**Comment by progre55** [comment]
+1! Can't wait for this!

**Comment by danielwhatmuff** [comment]
+1

**Comment by elgalu** [comment]
With github is now possible to +1 via "reactions" please avoid polluting issues with +1 comments, see:

[![IMAGE ALT TEXT HERE](https://cloud.githubusercontent.com/assets/25792/13683303/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif)](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)

**Comment by ylavoie** [comment]
I was looking for that too. I'm almost done, Hub & Firefox are working on Alpine, Chrome & PhantomJS will soon. I will PR my proposal.

**Comment by andrerom** [comment]
@ylavoie Found a way around issues in #224, or are they solved in alpine now?

**Comment by diemol** [comment]
Hi all, 

I just checked the packages for Chromium and Firefox, e.g.:
Chromium:
- https://pkgs.alpinelinux.org/package/v3.7/community/x86_64/chromium
- Latest release is 61.0.3163.100-r0, almost more than one month ago and the current Chrome version is >=63
Firefox:
- https://pkgs.alpinelinux.org/package/edge/testing/x86_64/firefox
- Is a bit more up to date, latest release 57.0.1 (current release is 57.0.2)

Even if the other dependencies are solved (like x11vnc), looks like the browser releases are way behind the releases from the browser vendor channels. We could be potentially blocked to use new browser versions since the new version package is not there yet for Alpine.

I would love to have smaller images, of course. But for me it seems that the all the effort plus having browsers not up to date is not really compensating the benefit of having smaller images.

What do you all think?

**Comment by ddavison** [comment]
not to mention, @diemol, Chromium != Google Chrome.   Users of Selenium might find that alarming if they want to test "Google Chrome" and get "Chromium"

**Comment by diemol** [comment]
Right, forgot to mention that as well @ddavison, you are totally right.

I'll close this issue based on the feedback gotten here and on #224
