### ISSUE TITLE
[🚀 Feature]: Is there still way how to install selenium grid into kubernetes without Helm ?

### ISSUE THREAD

**Issue by dironel** [SeleniumHQ/docker-selenium#1627]
### Feature and motivation

Is there still way how to install selenium grid into kubernetes without Helm ?

### Usage example

Is there still way how to install selenium grid into kubernetes without Helm ?

**Comment by diemol** [comment]
I believe you can get the manifest from the helm chart. 

💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well
