### ISSUE TITLE
[🚀 Feature]: Selenium node chrome docker windows image

### ISSUE THREAD

**Issue by refaeli-io** [SeleniumHQ/docker-selenium#1634]
### Feature and motivation

Hello, I wanna run my tests both on containers linux and xontainer windows. 
I want it because I want to uplaod windows pod on open ahift, as same I do with the node chrome image

### Usage example

As a part of the ci cd pipeline, we need ti check our system tests on different machines. Like linux and windows. 
When programer does a p.r then ee run an e2e testing on linux and scaling pod using keda, but the conatiner in the end are linux containers. 
I wish ro check it also for windows containers.
Thank you so much

**Comment by diemol** [comment]
We don't offer Windows images because Microsoft does not provide any images with Windows and a UI. Other projects offer workarounds but that involves building your own images and buying Windows licenses.

This was the original request to Microsoft and we didn't get a positive reply.

https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214

**Comment by refaeli-io** [comment]
O.k thank you very much🙏🙂
