### ISSUE TITLE
Getting "ignoring unsupported options shm_size" while executing Docker Swarm grig YML

### ISSUE THREAD

**Issue by tahir-akhlaq** [SeleniumHQ/docker-selenium#1667]
### What happened?

While running the "docker stack deploy -c docker-compose-v3-swarm.yml grid".

I'm getting ignoring unsupported options shm_size. Test cases are getting skipped giving the concurrentTimeOut Exception.
creating 41 replicas of Chrome browser.

<img width="830" alt="Screenshot 2022-09-02 at 4 49 02 PM" src="https://user-images.githubusercontent.com/101688815/188129572-d53e7ab9-6c65-44f1-97f3-16481960a67e.png">

### Command used to start Selenium Grid with Docker

```shell
version: '3.7'

services:
  chrome:
    image: selenium/node-chrome:4.4.0-20220831
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 41
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
 selenium-hub:
    image: selenium/hub:4.4.0-20220831
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

### Relevant log output

```shell
OS Arch: amd64

OS Name: Linux

OS Version: 5.10.118-111.515.amzn2.x86_64

Total slots: 1

Grid version: 4.4.0 (revision e5c75ed026a)
```

### Operating System

Amazon linux 2

### Docker Selenium version (tag)

4.4.0-20220831

**Comment by diemol** [comment]
https://github.com/moby/moby/issues/26714

Would you like to help us to improve the example file based on the recommendation?

**Comment by diemol** [comment]
I guess no time to help us improve the docs.

**Comment by aarahman7** [comment]
Hi @diemol, am still facing the same issue with the Docker Swarm. When I trigger the test cases, it launched and then again failed with WebDriverException.

I was getting "Ignoring unsupported options shm_size" and this message in WebDriverException:

unknown error: session deleted because of page crashfrom tab crashed (Session info: chrome=113.0.5672.63)Build info: version: '4.8.3', revision: 'e5e76298c3'System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3.1', java.version: '11.0.16.1'Driver info: org.openqa.selenium.remote.RemoteWebDriverCommand: 

I was going through the above document you shared and I was trying to implement this last comment:
https://github.com/moby/moby/issues/26714#issuecomment-579820612

This is my final Docker Swarm:
`
version: '3.8'

services:
  chrome:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_SESSION_TIMEOUT=600 #10 minutes
    deploy:
      replicas: 3
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    ports:
      - "7900:7900"
    tmpfs:
      - /tmp:size=2048M
    volumes:
      - type: tmpfs
        target: /app
        tmpfs:
          size: 2000000000 #2GB of memory
    networks:
      - default

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
`

Could you please help here?
