### ISSUE TITLE
[🚀 Feature]: Are there parameters that support setting browser language?

### ISSUE THREAD

**Issue by dzjwwm** [SeleniumHQ/docker-selenium#1671]
### Feature and motivation

After the browser starts, the default is English. I want to set it to Chinese. So, I set it in the code, but it doesn't take effect

### Usage example

```
from selenium import webdriver
import time

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--lang=zh_CN.UTF-8')
driver = webdriver.Remote(command_executor='http://localhost:4444', options=chrome_options)
driver.get("http://192.168.16.100:81")
driver.maximize_window()
time.sleep(5)
driver.quit()

```

**Comment by jamesmortensen** [comment]
Hi @tl31707chy I did some digging and found this issue:  https://github.com/SeleniumHQ/docker-selenium/issues/1009. Do you think the issue you're facing is the same here?  It seems like this may be a Chrome bug.

**Comment by jamesmortensen** [comment]
Thanks to https://stackoverflow.com/a/41893197/552792, I can launch a standalone-chrome container, and then in bash, I can start chrome using the LANGUAGE environment variable:

```bash
$ LANGUAGE=zh_CN.UTF-8 google-chrome
```

Then I get this result: 
<img width="1435" alt="Screenshot 2022-09-07 at 7 24 55 PM" src="https://user-images.githubusercontent.com/1315816/188896669-3f710004-b10e-499b-a869-958b6294f81e.png">

Since changing the language via an environment variable works, what you can do is start the container and set the environment variable at container launch time:

```bash
$ docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g -e LANGUAGE=zh_CN.UTF-8 selenium/standalone-chrome:latest
```

Additionally, not sure if the chrome_option specifying the language does anything or not.  You can try with and without to see if it's needed.

```python
from selenium import webdriver
import time

chrome_options = webdriver.ChromeOptions()
driver = webdriver.Remote(command_executor='http://localhost:4444', options=chrome_options)
driver.get("http://example.com")
driver.maximize_window()
time.sleep(5)
driver.quit()
```

**Comment by dzjwwm** [comment]
> 感谢https://stackoverflow.com/a/41893197/552792，我可以启动一个独立 chrome 容器，然后在 bash 中，我可以使用 LANGUAGE 环境变量启动 chrome：
> 
> ```shell
> $ LANGUAGE=zh_CN.UTF-8 google-chrome
> ```
> 
> 然后我得到这个结果： <img alt="截图 2022-09-07 在 7 24 55 PM" width="1435" src="https://user-images.githubusercontent.com/1315816/188896669-3f710004-b10e-499b-a869-958b6294f81e.png">
> 
> 由于通过环境变量更改语言是可行的，因此您可以做的是启动容器并在容器启动时设置环境变量：
> 
> ```shell
> $ docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g -e LANGUAGE=zh_CN.UTF-8 selenium/standalone-chrome:latest
> ```
> 
> 此外，不确定指定语言的 chrome_option 是否执行任何操作。您可以尝试使用和不使用，看看是否需要。
> 
> ```python
> from selenium import webdriver
> import time
> 
> chrome_options = webdriver.ChromeOptions()
> driver = webdriver.Remote(command_executor='http://localhost:4444', options=chrome_options)
> driver.get("http://example.com")
> driver.maximize_window()
> time.sleep(5)
> driver.quit()
> ```

okay, thank you

**Comment by jamesmortensen** [comment]
You're welcome!
