### ISSUE TITLE
[🚀 Feature]: Please provide an overview of possible environment variables and their effect, to pass to the docker container.

### ISSUE THREAD

**Issue by MajesticOl** [SeleniumHQ/docker-selenium#1805]
### Feature and motivation

I am having a really hard time doing simple things like configuring the browser instance count within a node because there seems to be no information whatsoever of which environmental variables are available for configuration. Cant you provide a simple overview ? 

### Usage example

I would use it to get an overview of all the possible configuration.

**Comment by diemol** [comment]
I believe most of them are documented, but likely some of them are missing. Which variables did you miss docs. The complete Grid documentation is here https://www.selenium.dev/documentation/grid/, and in most of the cases there is an env var for each case.

**Comment by MajesticOl** [comment]
I cannot find the environmental variables inside the documentation to save m life... Where can i find it ? There is nothing in the configuration section resembling any env variables. Sorry i a m blind it seems.

**Comment by diemol** [comment]
What are you looking for? The env vars are not shown there, the parameters are shown there https://www.selenium.dev/documentation/grid/configuration/

Is there something specific you are looking for?

**Comment by MajesticOl** [comment]
Well im looking for all the env variables... an overview to be able to configure my kubernetes environment properly. I mean its a docker project after all... the env variables are what really matters in terms of configuration ^^

I specifically want to know how to increase session and browser instance count through the environment for starters.

**Comment by diemol** [comment]
That is why I was asking if you were looking for something specific. Those two are already documented

- I guess you meant session timeout -> https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout
- Browser instances -> https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container

Most of the env vars are documented. There might a couple that are not. 

We are a reduced team and this task has low priority because the README has a large amount of cases well documented. We would appreciate your help to complete this task, with that you can also become a contributor!

**Comment by diemol** [comment]
@MajesticOl any chance you got my previous comment?
