### ISSUE TITLE
[🚀 Feature]: Upgrade Python to the latest version

### ISSUE THREAD

**Issue by tanguy-fgl** [SeleniumHQ/docker-selenium#1876]
### Feature and motivation

Upgrade Python version to the latest version . It fixes a lot of security & performance issues. Today projects are using Python 3.9 and 3.10 at minium version. Personnaly, I need to use Python 3.10 for my project.

### Usage example

I don't have any examples

**Comment by diemol** [comment]
We use the version that comes with the base Ubuntu image. The version present in the images is not provided to be used by end users. If you need a different version, you should install it.

**Comment by tanguy-fgl** [comment]
How ?

**Comment by diemol** [comment]
This shows how an image can be extended [FROM ](https://github.com/SeleniumHQ/docker-selenium#install-certificates-for-chromium-based-browsers), but instead of installing certificates, do something like this https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

If you have more questions, I will leave some links below.
