### ISSUE TITLE
Investigate X11 forwarding as opposed to VNC

### ISSUE THREAD

**Issue by mtscout6** [SeleniumHQ/docker-selenium#2]
Initial issue derived from elgalu/docker-selenium#10

According to the [Docker Official Repo Guidelines](https://docs.docker.com/docker-hub/official_repos/) These images should not derive from `phusion/baseimage`. However, the initial reason to base off that image was to provide stability when running a Selenium node with VNC and Xvfb support.

There was an [IRC conversation](https://botbot.me/freenode/docker-library/2014-11-06/?tz=America/Denver) with @psftw regarding a possible means of utilizing a separate container for debug purposes using X11 forwarding. This approach would remove the need to support VNC in the same container as the Selenium node, thus getting us one step closer to a more efficient image. 

I have done some initial work on this on my personal [x11 branch](https://github.com/mtscout6/docker-selenium/tree/x11) which is still a ROUGH DRAFT. In there I was able to achieve using Xvfb and the Selenium node in a single process tree. The next goal is to figure out how to attach another container and perform an SSH connection with X11 forwarding.

**Comment by neural-wetware** [comment]
How about we just expose the X server domain socket in a volume like this:

http://stackoverflow.com/a/25168483

**Comment by elgalu** [comment]
> It grants the container full access to the xserver on the host

**Comment by BrennanRoberts** [comment]
Just to clarify, is the current usage of `xvfb` incompatible with the approach of mounting the host's X socket in, say, a `StandaloneChrome` container?

**Comment by BrennanRoberts** [comment]
Correct me if I'm wrong, but I believe the answer to ^ is "yes". `xvfb` sets up it's own X server, which is diametrically opposed to passing the socket from the host's X server in. Unwrapping the `java ... -jar /opt/selenium/selenium-server-standalone.jar` from `xvfb-run`, and passing `DISPLAY`/mounting `/tmp/.X11-unix` at `docker run` time works as desired. 

Would an option to bypass the `xvfb-run` segment of each entrypoint be an acceptable solution?

**Comment by elgalu** [comment]
I agree is now incompatible as of now.

I confirmed the x11 redirect works ~1yr ago on version [v2.46.0-x11](https://github.com/elgalu/docker-selenium/blob/master/CHANGELOG.md#v2460-x11) while playing with [Xephyr to redirect X to the docker host](https://github.com/elgalu/docker-selenium/tree/v2.46.0-x11#using-xephyr-to-redirect-x-to-the-docker-host) and passing `-v /tmp/.X11-unix/X${XE_DISP_NUM}:/tmp/.X11-unix/X${XE_DISP_NUM}` among other things.

But drop it after because didn't really want to support this use case back then but if someone wants to implement it for real and become officially supported that might help.

**Comment by BrennanRoberts** [comment]
Pushed #346 and looking for feedback.

**Comment by diemol** [comment]
Hi all, 

Is this still relevant? This issue and the PR have been stale for ~1.5 years.

**Comment by diemol** [comment]
Closing issue since it is completely stale (also the related PR).
