### ISSUE TITLE
Improve image building process

### ISSUE THREAD

**Issue by kayabendroth** [SeleniumHQ/docker-selenium#213]
Improve the image building process to prevent regressions like https://github.com/SeleniumHQ/docker-selenium/issues/208.

Currently images are built by hub.docker.com for the branches that have been configured (master, 2.52.0 and 2.53.0 currently). Code changes trigger only one image build (per branch) and all subsequent image builds are triggered by the previous image changing.

Problems:
- Images build off of master depend on the images build for the "current version branch" (2.53.0 right now), which can lead to inconsistencies.
- Changes in master that you want to have in one of the version-tagged images have to be merged into the corresponding branch.
- The images we build in CircleCI are not the ones you later download from the registry.
- Building images for a new Selenium version requires a new branch in the repo and a configuration change on hub.docker.com.

**Comment by kayabendroth** [comment]
@davehunt already suggested to have ```latest``` images derived from the ```latest``` base images.

**Comment by rubytester** [comment]
I setup that build chain in docker hub, and yes, it does require that manual step to know that when master branch builds latest image you need the branch name.... That is crappy, sorry for leaving you in a bad state. (quick note on that process https://github.com/SeleniumHQ/docker-selenium/wiki/Docker-hub-automated-builds)

With the way Dockerfile is produced constructing FROM stanza with version number (based on branch) perhaps we should not build on master branch automatically but only build on branch name. That way when you merge  into master the trigger will not fire on docker hub, only when you advance the branch to the desired sha the docker will trigger the build. (this is still a manual process of someone merging master into branch and pushing to github)

Or change the FROM stanza to have 'latest' instead of a version number. Then builds will trigger on every master advance automatically. (but now some manual process may be needed to tag it with version number if needed)

Sorry but I have not worked with these images much, my job has moved to something else in the last few months.

**Comment by ddavison** [comment]
I believe i will have this covered with the changes i've been working on.   i will update this issue with details (and hopefully a wiki page for maintainers for docker-selenium)

**Comment by diemol** [comment]
I think this was already accomplished by @ddavisona while ago, right? This issue should be closed then.
