### ISSUE TITLE
selenium chromedriver hangs

### ISSUE THREAD

**Issue by rajaashutosh** [SeleniumHQ/docker-selenium#222]
Hi,

I am doing Selenium Automation in C# and Use following drivers.
Chromium.ChromeDriver" version="2.21" 
NUnit version="3.2.1" 
Selenium.Support version="2.53.0" 
Selenium.WebDriver version="2.53.0"

All the test cases working fine,however when i connect the same test case in Build tool, then after some test case get executed, automatically google chorme hangs. I dont know the issue and even i am new to selenium. Please Guide me.

Thanks In Advance :)

**Comment by zypherman** [comment]
See https://github.com/SeleniumHQ/docker-selenium/issues/87
Add to your docker file:
export DBUS_SESSION_BUS_ADDRESS=/dev/null
or environment:
    DBUS_SESSION_BUS_ADDRESS:/dev/null
if you are using docker compose.

**Comment by kayabendroth** [comment]
@rajaashutosh Did this fix it for you?

**Comment by jojojoy2k** [comment]
@rajaashutosh It would be nice to have a reply on whether the proposed solution fixed your issue. Thanks!

**Comment by dhtlee** [comment]
The problem seems to be with Chromedriver version 2.21, which is used by the latest docker image on the public docker hub. Issue should be fixed once Selenium updates the Chromedriver version on the official docker image.

In the meantime, vpbonev checked in a [fix](https://github.com/SeleniumHQ/docker-selenium/pull/260/commits/5cc1ce1444504f5752754fd512093bc6a0501719) that updates to Chromedriver version 2.23. You can clone docker-selenium project and build your Chrome (or ChromeDebug) image off that Dockerfile

**Comment by diemol** [comment]
This was fixed with #469 
@ddavison I think this issue can be closed.
