### ISSUE TITLE
Browser updates

### ISSUE THREAD

**Issue by matthewb531** [SeleniumHQ/docker-selenium#229]
Hi team

How often are the browser versions on Selenium-Docker updated? 

Is it fair to trust that they will be kept quite up-to-date? And is the typical update frequency different for Chrome vs. for Firefox?

Side note: I noticed, read about and now understand why the Firefox basenode Dockerfile is hard-coded to v45 for now. But I'm more interested in if browser versions are kept up to date in general.

Kind regards
Matthew

**Comment by elgalu** [comment]
Good question, so far is based on the maintainers free time to manually (via commits) trigger the builds and test them in order to keep them up to date. It would be nice to have this automated somehow, see issue https://github.com/elgalu/docker-selenium/issues/81 on the side project.

**Comment by matthewb531** [comment]
Thanks @elgalu! 

Does anyone have any idea on how often that updating has taken place historically? Even very generally? 
Like is it ...every month? or every year? or? Just any sort of indication would be a great help.

**Comment by elgalu** [comment]
Welcome @matthewb531. So in the [side project](https://github.com/elgalu/docker-selenium#usage), by looking at the [releases tags](https://github.com/elgalu/docker-selenium/tags) I see it requires me 1 release every 7 days, more or less, meaning there is at least a new version of either Chrome or FF or Selenium every week but as I said, checking and doing this manually.

**Comment by bartslaman** [comment]
So when like firefox 47 is not compatible with Selenium  xxxx I assume you don't upgrade to 47 right?

**Comment by elgalu** [comment]
Correct, I tried in the other project and it fails: https://github.com/elgalu/docker-selenium/issues/102

**Comment by gortazar** [comment]
Given that FF 47.0.1 works with Selenium 2.53.1, are there any plans to upgrade to 2.53.1?

**Comment by ddavison** [comment]
as the new maintainer of the project, i've been making sure that all browser versions are copacetic with the Selenium version released.

as far as the browser versions being updated, I will update them when they need it.  For example, 3.0.0 is coming out, and it rules out RC.  I will bump the FF version to 49, since Selenium 3.0.0 requires geckodriver. 

all this being said, if you need to specify your own versions, I recommend that you build your own images.

If you wanted to build a docker container with Firefox version 48, you can do that.

pull our code down, then you can utilize our Makefile, or just use plain-ol-docker.

```bash
$ docker build -t my-firefox-image --build-arg FIREFOX_VERSION=48.0.1 NodeFirefox
$ docker build -t my-firefox-image --build-arg FIREFOX_VERSION=48.0.1 NodeFirefoxDebug
$ docker build -t my-firefox-image --build-arg FIREFOX_VERSION=48.0.1 StandaloneFirefox
$ docker build -t my-firefox-image --build-arg FIREFOX_VERSION=48.0.1 StandaloneFirefoxDebug
```

or using our Makefile

```bash
$ BUILD_ARGS="--build-arg FIREFOX_VERSION=48.0.1" make firefox firefox_debug standalone_firefox standalone_firefox_debug
```
