### ISSUE TITLE
Different behaviour between FirefoxNode and FirefoxNodeDebug

### ISSUE THREAD

**Issue by azakordonets** [SeleniumHQ/docker-selenium#247]
Hi, I'm experiencing very weird behaviour. On TeamCity, we are running tests towards Selenium grid that is using FirefoxNode image . It's headless and with this node, i get a failure on the test because the link doesn't get clicked. If I re-run this tests, but towards FirefoxNodeDebug, and look at it in VNC viewer, then WebDriver clicks on a link from the first time and it works. I don't understand how this could be possible - clicks should behave same in headless and non-headless mode. Any tips on where to look or what to try would be very appreciated.

**Comment by nuggit32** [comment]
I suggest taking a screenshot at the time of failure and see if the element is present.  I've had issues like this before and seen that the element is not present to click when in Headless mode because of the browser rendering (instead a Hamburger Icon needed click to get to the menu element).  I was able to debug this with a screenshot to see the problem.  Also, what is the exception that is being called?  Element not found?

**Comment by azakordonets** [comment]
It's been could of weeks when i had this problem. I'm not sure, but i think you're right - the problem is in rendering difference in headless and non-headless mode. Will try to add some waits
