### ISSUE TITLE
Don't reuse docker tags: include the browser version in the docker tags

### ISSUE THREAD

**Issue by JoepWeijers** [SeleniumHQ/docker-selenium#280]
The Docker tags only contain the current Selenium version, for example 2.53.0. Every commit triggers a new build, every build grabs the latest version of a browser and this build is re-released under the same tag. This results in the less than ideal situation where the `selenium/standalone-chrome:2.53.0` I pulled some months ago contains Chrome 50, and if I pull it today it will contain Chrome 53.

This poses a problem if the latest browser is not compatible with the current selenium: FF47 requires selenium 2.53.1, but a 2.53.0 build is run that includes the latest Firefox, so it is now broken. Chrome 53 requires a newer Chromedriver, but a 2.53.0 build is run, so it includes this latest Chrome anyway, so now it is broken as well. 

The best solution would to not reuse docker tags at all and ensuring that every released tag points to only one version of the code. Or use an alternative tagging scheme: somehow include the browser version in the docker tags, like: 2.53.0_chrome50 and 2.53.0_chrome51. You can still keep the 2.53.0 tag to indicate the latest 2.53.0 release, but this at least enables people to rollback to an other selenium / browser combination, something which is not possible now.

**Comment by ddavison** [comment]
ref: https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile.txt#L15

**Comment by ddavison** [comment]
i believe the reason that we have it set up that way, is because of hot-fixes.  if we need to release something to 2.52.0 we can just push to the branch and have it updated.  as far as the Chrome part, you are able to specify that now (take a look at the ref in my comment above.)  if you need to specify a version, you will be able to.

there is definitely room for discussion on tagging, but i'm still not sure how to best tackle it right now.  

on the contrary however, I think it would be useful to "not" have branches and purely use tags.  i'll definitely keep this in mind.

**Comment by FelikZ** [comment]
@ddavison you can specify Chrome version but it means that you have to build image on your own, i.e. official docker images become useless because they are unstable...
