### ISSUE TITLE
no focus behavior on firefox in standalone-firefox-debug container

### ISSUE THREAD

**Issue by linzkl** [SeleniumHQ/docker-selenium#308]
## Meta -

Image(s):  95ce2800e312 standalone-firefox-debug

Docker Version:  latest

## Behavior -

I'm having issue when using standalone firefox debug to execute some of my ruby selenium code. I tested the same code in chrome debug version, and also tested in local firefox without using container, they were working fine. The behavior is in the website there has some angularjs masking logic, based on the monitoring from VNC, seems after setting the value to that field, there is no obvious focus on or out of this text field to trigger the masking. Our testing ruby code using datamagic, which using **self.send "#{key}=", value** to set the field value.

Not quite sure why it will behavior differently from local firefox or standalone-chrome-debug.

Thanks

**Comment by jmbowman** [comment]
I'm hitting something similar; it seems that when the browser window is launched, the OS doesn't consider it to have focus.  If I connect via VNC and click on the window before the focus-related tests run, they all pass; otherwise, they fail.  I'm looking into workarounds like the ones described [here](https://stackoverflow.com/questions/10649637/make-sure-that-browser-opened-by-webdriver-is-always-in-focus), but it would really help if the launched window had focus by default.

**Comment by jmbowman** [comment]
I did find a workaround for this: enabling the "focusmanager.testmode" Firefox preference.  This had been made the default when launched from Selenium FirefoxDriver around Firefox 42 or so, but it is apparently no longer enabled by default when launching newer Firefox versions via geckodriver.  I'm not sure if enabling it by default in the image is a good idea or not, but it probably at least merits a mention in the README as a common pitfall when testing focus-related functionality.

**Comment by diemol** [comment]
I was googling a bit about it, and most of my findings point to what you suggest @jmbowman, even documented in some [test suite](https://openedx.atlassian.net/wiki/spaces/PLAT/pages/161837611/Automated+Tests+Browser+Compatibility).

If you feel like, you can help us and add the info into the [Wiki section](https://github.com/SeleniumHQ/docker-selenium/wiki) of this repo.

I'll close this issue since it was solved by the previous comment.
