### ISSUE TITLE
Override Locales

### ISSUE THREAD

**Issue by zuernBernhard** [SeleniumHQ/docker-selenium#314]
It would be great to be able to override the local from the dockerfiles eg de_DE.UTF-8 instead of en_US.UTF-8 how is that possible without forking the repo and hacking the dockerfile ? It would be grad to be able to override the ENV-Variables for example with docker-compose. But its hard-wired for the local-gen comman in the Dockerfile:

```
#=================
# Locale settings
#=================
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
RUN locale-gen en_US.UTF-8 \
  && dpkg-reconfigure --frontend noninteractive locales \
  && apt-get update -qqy \
  && apt-get -qqy --no-install-recommends install \
    language-pack-en \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

```

**Comment by porsuv** [comment]
Can you please explain steps how to setting up language specific by hacking?
I am new to docker.

**Comment by porsuv** [comment]
I can build the image file with above suggested setting to my locale.
However, the web events can do events on my language on xpath but the capture screen on browser is still unreadable for human.
Have  you ever seen this issue ?

**Comment by diemol** [comment]
Hi @zuernBernhard,

Sorry for replying so late to this issue. 

In the most recent release, we moved the locale setting part to the base node and we changed it slightly to use env vars, so now it is possible to pass these values and you could build a customised image. Please check https://github.com/SeleniumHQ/docker-selenium/blob/3.11.0-californium/NodeBase/Dockerfile.txt#L14

The following link shows how you could build your own image:
https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images

If you are still looking for this change, please give it a try and give us feedback by writing a comment here.

I'll close this issue since the locale generation is not hardcoded anymore and an env var is used. If any issue is found, please don't doubt to comment or reopen.

**Comment by zuernBernhard** [comment]
Better late than never. Thank you a lot !!
