### ISSUE TITLE
Any plans to add additional browser support?

### ISSUE THREAD

**Issue by pfluegs** [SeleniumHQ/docker-selenium#350]
Just curious if there are any plans to add node images for Safari or IE?

**Comment by asethi15** [comment]
I have the same need to have IE in a selenium/standalone-IE-debug image. Any plans?

**Comment by ddavison** [comment]
the thing to think about, is that in order to support these browsers, they need their respective operating systems.

the problem is - Windows and MacOSX would need to be containerized first in order to run their respective browsers.  I believe Microsoft is in the process of this, but who knows if Apple would ever do this.

So - @pfluegs and @asethi15; at this juncture it is impossible, however I will have my eye out to see if they release those containers.
