### ISSUE TITLE
Unable to build node-chrome image using docker file

### ISSUE THREAD

**Issue by rajivbhati12** [SeleniumHQ/docker-selenium#361]
## Meta -
Docker file source: https://github.com/SeleniumHQ/docker-selenium/raw/master/NodeChrome/Dockerfile
Image(s):  N/A

Docker Version:  1.12.2, build bb80604

 ## Expected Behavior - 
Line# 53 ---> COPY chrome_launcher.sh /opt/google/chrome/google-chrome
Should copy chrome_launcher.sh to dir -> google-chrome
## Actual Behavior -
google-chrome is a file that gets populated before cursor reach line#53 and hence get fail as it is not valid destination.

**Comment by ddavison** [comment]
can you share the command you are using to build the image?  I'm not getting this error, nor is our CI

**Comment by rajivbhati12** [comment]
My goal is to successfully build chrome image using same command as you have:

My [Dockerfile.txt](https://github.com/SeleniumHQ/docker-selenium/files/694347/Dockerfile.txt)
build command `docker build -t "rajivbhati12/ubuntu_w_node_chrome:v1" .`

I copy code from [Dockefile](https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/master/NodeChrome/Dockerfile), and made 2 changes
1. It use ubuntu:latest as base image with Sudo and wget installed
2. Create directory before copy chrome_launcher.sh `RUN mkdir -p /opt/google/chrome/google-chrome` 

Observation: build process run good until it reach `mkdir` 
Actions: I remove `mkdir` but it result into fail:  `/opt/google/chrome/google-chrome ` dir not exist 
Solution: I copy chrome_launcher.sh to `/opt/google/chrome`, make corresponding changes and then I was able to use it as chrome node.

**Comment by ddavison** [comment]
i'm really just not sure what to do here.  you're clearly using your own changes to our images, so there are too many variables i cannot account for.  since this isn't a problem with our repository, i can't really do anything.

if you find that this is truly an issue with the selenium images, then i will happily reopen, but since we have these images being built and tested in a continuous integration server, i can clearly see that  this isn't a problem with our production images
