### ISSUE TITLE
REMOTE_HOST variable is DEPRECATED

### ISSUE THREAD

**Issue by dexter999999** [SeleniumHQ/docker-selenium#401]
## Meta -
Image(s):  
 node-chrome
Docker Version:  
OS: AWS RED HAT Linux

how would I get this working on 2 Ec2 instances , 1 being the Hub and the other that had 50 Chrome Nodes

Used to use this command to connect to a hub on a diff ec2 machine

##Expected
docker run -d -p 901:5555 -e REMOTE_HOST=xx.xx.xx.xxx:901 -e HUB_PORT_4444_TCP_ADDR=yy.xy.xy.xy -e HUB_PORT_4444_TCP_PORT=4444 --name chrome901 seleniumchrome:54.0.2
REMOTE_HOST variable is *DEPRECATED* in these docker containers. Please use SE_OPTS="-host <host> -port <port>" instead!

Then I tried with SE_OPTS

##Actual
docker run -d -p 103:5555 -e SE_OPTS="-host xx.xx.xx.xxx -port 102" -e HUB_PORT_4444_TCP_ADDR=yy.xy.xy.xy  -e HUB_PORT_4444_TCP_PORT=4444 --name chrome103 seleniumchrome:54.0.2

##OUTPUT chrome container logs:

> appending selenium options: -host 10.205.74.185 -port 102
> Waiting xvfb...
> -bash: 10.205.74.185: command not found
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...
> /opt/bin/entry_point.sh: line 62: fluxbox: command not found
> /opt/bin/entry_point.sh: line 64: x11vnc: command not found

It is similar to issue #307 

not sure how i can introduce the SE_OPTS variable , any help would be appreciated

**Comment by ddavison** [comment]
you are using the image: `"seleniumchrome:54.0.2"`  which image is this? this is not ours.  did you build this yourself?

**Comment by saifsysim** [comment]
This is an Image we we built ourselves, its just the same thing as yours. we tried 

> `
sudo docker run -d  -p 5555:5555 -e HUB_PORT_4444_TCP_ADDR=<your_grid_ip> -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS='-hub $HOSTNAME -port 5555' --name chrome55node1 selenium-chrome:55.0.0 /bin/bash /opt/bin/entry_point.sh`

> appending selenium options: -host 10.xXX.xx.xx -port 5555
> Waiting xvfb...
> -bash: 10.xxx.xx.xx: command not found
> Waiting xvfb...
> Waiting xvfb...
> Waiting xvfb...

**Comment by jaeckmar** [comment]
I recently used SE_OPTS instead of REMOTE_HOST variable but it doesn't work. 

`docker run -d -p $HUB_PORT:5555 -p $VNC_PORT:5900 -e SE_OPTS="-host $DOCKER_HOST_IP -port $HUB_PORT -browser browserName=firefox,maxInstances=1" -e HUB_PORT_4444_TCP_ADDR=<myjenkinsdns> -e HUB_PORT_4444_TCP_PORT=4444 --name $CONTAINER_NAME-$n selenium/node-$BROWSER:$SELENIUM_VERSION`

where parameters are like this
CONTAINER_NAME=sel-node
BROWSER=firefox
#SELENIUM_VERSION=2.53.0
SELENIUM_VERSION=3.1.0-astatine
DOCKER_HOST_IP=<myIp>
HUB_PORT=<aPort>

same configuration works when using selenium v 2.53.0 with REMOTE_HOST variable set to REMOTE_HOST=http://$DOCKER_HOST_IP:$HUB_PORT instead of SE_OPTS. requesting that REMOTE_HOST via browser I previously got a response (jetty). with new version I failed to connect to m running docker container

Any ideas?

**Comment by diemol** [comment]
@saifsysim I think this issue is the same one as #423, hopefully your setup should work when #459 gets merged (or you could just check the commits and adapt them to your image).

**Comment by diemol** [comment]
This is fixed by #459, this issue can be closed.

**Comment by diemol** [comment]
@ddavison can you please close this issue?
