### ISSUE TITLE
Passing ARG to node-chrome-debug in docker-compose.yml

### ISSUE THREAD

**Issue by finspin** [SeleniumHQ/docker-selenium#409]
I'm trying to pass chrome version in my docker-compose.yml but I'm getting `Unsupported config option for chromenode: 'args'`. Is there a way to pass it?

    seleniumhub:
      image: selenium/hub
      environment:
        - GRID_MAX_SESSION=10
        - GRID_BROWSER_TIMEOUT=100000
        - GRID_TIMEOUT=90000
        - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
      ports:
        - 4444:4444

    chromenode:
      image: selenium/node-chrome-debug
      # image: selenium/node-chrome
      ports:
        # port for VNC viewer
        - 5901:5900
      args:
        - CHROME_VERSION=google-chrome-stable=53.0.2785.101-1
      environment:
        - NODE_MAX_SESSION=10
        - NODE_MAX_INSTANCES=10
      links:
        - seleniumhub:hub
      volumes:
        # use host's shared memory when running chrome
        - /dev/shm:/dev/shm

**Comment by ddavison** [comment]
`CHROME_VERSION` is a build argument, not an environment variable.  Here is the main difference:

> **Docker Build Argument** - (*Specified by `ARG`*); Cannot specify these arguments at runtime like environment variables. They are used as arguments to build the actual docker containers.

> **Docker Environment Variables** - (*Specified by `ENV`*); Runtime environment variables.  Allowed to be set during running of the docker containers.

The problem you are having, @finspin is that you are trying to use a build argument like an environment variable, therefore it doesn't work.  Take a look at [`ARG CHROME_VERSION`](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile#L20) and [`ENV NODE_MAX_SESSION`](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/Dockerfile#L45)

Notice CHROME_VERSION is an arg, and NODE_MAX_SESSION is an env variable.

So - in order to use the google chrome version that you wish, you need to [build your own image](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images#specify-chromedriver-and-chrome-versions).
