### ISSUE TITLE
Unable To Run Multiple Nodes On 5555 Internally With Various Ports Mapped Externally

### ISSUE THREAD

**Issue by tparikka** [SeleniumHQ/docker-selenium#432]
## Meta -
Image(s):  selenium/node-chrome:3.2.0
Docker Version: Version 17.03.1-ce-win5 (10743)
OS: Windows 10

## Summary

In order to work around an issue in Docker for Windows (issue 426) with container listening ports failing under heavy load, I'm attempting to run a set of node-chrome instances using docker run and just run the hub (which is the container whose listener fails) locally. To do this, I attempted to run as follows:

`docker run -d --name node101 -p 5595:5555 -e HUB_PORT_4444_TCP_ADDR=10.10.1.10 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 10.10.1.10 -port 5595" selenium/node-chrome:3.2.0`

I'm providing the address of the hub server, mapping a public port 5556 to the internal port 5555 (which is the default running port of the node), and using SE_OPTS to report the external facing IP and port of the node. Since `-p 5955:5555` binds the container's port mapping listener to 0.0.0.0 (as confirmed via netstat -a) any of my locally assigned IPs should work from my understanding. However, when I do this, the hub instance (also running 3.2.0) shows the following error in the Grid Console:

![image](https://cloud.githubusercontent.com/assets/7715790/24583715/371f72fa-1719-11e7-8511-0ef1c826eab7.png)

The log repeats the following until the session finally dies:

`20:24:54.014 INFO - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://10.10.1.10:5595: The target server failed to respond`

`20:24:54.015 INFO - Retrying request to {}->http://10.10.1.10:5595`

However, if I manually set the NODE_PORT of each node and do a 1:1 port mapping (no translation) of each separate Node like so, it works correctly:

`docker run -d --name node10 -p 5564:5564 -e HUB_PORT_4444_TCP_ADDR=10.10.1.10 -e HUB_PORT_4444_TCP_PORT=4444 -e NODE_PORT=5564 -e SE_OPTS="-host 10.10.1.10 -port 5564" selenium/node-chrome:3.2.0`

## Expected Behavior -

I had expected that I could expose a unique port for each node container and forward that port from the host to 5555 on the container and use SE_OPTS to tell the Hub what host and port to use for the return connection. 

## Actual Behavior -

Unless I give each node instance a unique port number and provide the NODE_PORT environment value to override the default of 5555 the hub isn't able to talk to the node. Unless this is expected?

**Comment by diemol** [comment]
Can you please post, step by step, how you start the hub and then each one of the nodes?

It is not so easy to understand what you wrote without all the commands.

**Comment by tparikka** [comment]
I listed all of the commands (except the hub startup) in my original report above.

Step 1: Start the hub with `java -jar C:\SeleniumGrid\selenium-server-standalone-3.0.1.jar -role hub -maxSession 20` (the hub is operating on a machine with the address 10.10.1.10 bound to a local NIC)
Step 2: Start the node with `docker run -d --name node101 -p 5595:5555 -e HUB_PORT_4444_TCP_ADDR=10.10.1.10 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 10.10.1.10 -port 5595" selenium/node-chrome:3.2.0`

Where I used 5595 in the -p argument and in SE_OPTS to expose the public-facing port I also tried 5556, 5557, 5558, and other values with no success.

**Comment by diemol** [comment]
Ah OK, that was were I got lost, didn't know how the hub was started :) 
I will check it and see if it works for me.

**Comment by tparikka** [comment]
Thank you! I appreciate your time! Let me know if there's any other logs or system info I can provide, or things I should try. I'll be out this afternoon with family but I'll be back around tonight, and then more available tomorrow morning.

**Comment by diemol** [comment]
The first thing I saw is that you should try to use a version in the hub equal or bigger than the nodes, you were starting the hub with version 3.0.1 and using nodes with version 3.2.0. _This is not actually the problem, but it is a good practice to have a bigger or equal version at the hub._

So, I started the hub with this command:
```sh
java -jar selenium-server-standalone-3.3.1.jar -role hub -maxSession 20
``` 

My machine currently has the IP `192.168.2.103`, so the hub is at http://192.168.2.103:4444/grid/console.

When I start the node with:
```sh
docker run -d --name node101 -p 5595:5555 -e HUB_PORT_4444_TCP_ADDR=192.168.2.103 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 192.168.2.103 -port 5595" selenium/node-chrome:3.3.1
```
It won't work, because the node is running inside the container with the port 5595, but the mapped one internally is 5555. This means that the hub will try to reach http://192.168.2.103:5595, and 5595 is mapped to 5555 inside the container, but there is nothing running on 5555 inside the container.

So, just start the node mapping the ports `5595:5595`, no need to use the `NODE_PORT` parameter.
```sh
docker run -d --name node101 -p 5595:5595 -e HUB_PORT_4444_TCP_ADDR=192.168.2.103 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 192.168.2.103 -port 5595" selenium/node-chrome:3.3.1
```

I think it is not possible to use a unique port inside the container and different ports outside it because the node will register itself with the port that is using inside the container. Therefore the hub will try to reach the node through the port used for the registration, but it won't reach it since the mapped one is different.

**Comment by tparikka** [comment]
@diemol Good catch on the hub version - I hadn't updated the Selenium version on my VM grid in a while, so I did that after seeing your update. What I was anticipating was the ability to forward a designated publicly-facing port through Docker's external network stack to the default internal port of 5555 (using -p for docker run or the "ports" argument for compose), and then SE_OPTS (which was the replacement for REMOTE_HOST) to direct the Hub to connect back to a specific port exposed by Docker which would then be forwarded back to 5555 internally on the node container.

If this is officially NOT supported and there is no intent to ever support functionality like this, I can close the issue. I'd appreciate a maintainer verifying though before I do so.

**Comment by diemol** [comment]
@tparikka when you pass `-port 5595` in the `SE_OPTS` you are telling the Selenium node to use that port to listen to incoming requests. But the mapped port internally is `5555`, therefore it will never be reached.

This part:
> to direct the Hub to connect back to a specific port exposed by Docker which would then be forwarded back to 5555 internally on the node container

is basically port forwarding, and to my knowledge, this is usually done with a proxy like nginx. In my opinion, setting up something like that in docker-selenium is out of the scope.

**Comment by McSnowflake** [comment]
@diemol @tparikka 
This is exactly what the REMOTE_HOST param has been for. It told the node to tell the hub a specific url to connect to without touching the nodes actual configuration and this way allowing portmapping to be part of the setup.

**Comment by diemol** [comment]
Since I have seen a some issues that talk about the same topic (REMOTE_HOST, reporting a different IP/Port in different network topologies, etc...), here is what I have found:

@tparikka, so what you wanted to achieve is actually possible, and no port forwarding is needed. The REMOTE_HOST parameter [support was removed from the nodeConfig.json](https://github.com/SeleniumHQ/docker-selenium/issues/481#issuecomment-300607612), but you could still use it in the parameters when starting a node. Summarising, you can:

Start hub:
```
docker run -p 4444:4444 --name selenium-hub selenium/hub:3.7.1-beryllium
``` 

Start node:

```
docker run --name node101 -p 5595:5555 \
    -e HUB_PORT_4444_TCP_ADDR=192.168.1.7 \
    -e HUB_PORT_4444_TCP_PORT=4444 \
    -e SE_OPTS="-remoteHost http://192.168.1.7:5595" \
    selenium/node-chrome:3.7.1-beryllium
```

So you have inside the container port 5555, externally 5595, and the hub will reach node like that.
