### ISSUE TITLE
support for servo and servo `./mach.sh --headless`

### ISSUE THREAD

**Issue by graingert** [SeleniumHQ/docker-selenium#482]
Feature request, [servo](https://github.com/servo/servo) seems to support headless browsing (no xvfb) and webdriver natively. Would be nice to have this as an option.

**Comment by diemol** [comment]
Do you know if there is a docker image already with it? I didn't find anything.

**Comment by diemol** [comment]
I was checking this again, and if I understood correctly, servo is a browser engine and not really a browser that people use. 

Considering that Selenium is going in the direction of supporting only real browsers (e.g. PhantomJS  is in a deprecated status since Selenium version 3.6.0), it would not make sense to include this one.

Therefore, I'll close this issue. But feel free to reopen if I am mistaken, or if there are stronger arguments from the community for this.

**Comment by graingert** [comment]
Fyi Firefox 57 has all the cool bits of servo, and it's headless!  Let's drop xvfb totally from the 3.7 images!!
