### ISSUE TITLE
Chrome Containers --> too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)

### ISSUE THREAD

**Issue by gokulganthtm** [SeleniumHQ/docker-selenium#490]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):    Latest version 
Selenium/node-chrome-debug and Selenium/node-chrome

OS: 
LINUX OPEN SUSE

## Actual Behavior -  Chrome Container opens up the browser, but without entering some values in the Text filed...Waits for some time and throws readtimeout Error.

My Docker compose file 

  selenium-hub:
    image: selenium/hub
    ports:
      - 4446:4444
    environment:
     GRID_BROWSER_TIMEOUT: 300000
     GRID_TIMEOUT: 150000
     GRID_MAX_SESSION: 50
   
  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - 5900
    environment:
      DBUS_SESSION_BUS_ADDRESS: /dev/null
      NODE_MAX_INSTANCES: 2
      NODE_MAX_SESSION: 2
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1480
    volumes:
     - /dev/shm:/dev/shm
    links:
      - selenium-hub:hub

**Comment by diemol** [comment]
Hi @gokulganthtm,

I googled the error and the first two results are issues created in the docker-selenium and selenium projects respectively, did you check the solutions provided there?

https://github.com/seleniumhq/selenium/issues/1158
https://github.com/SeleniumHQ/docker-selenium/issues/198

If the solutions mentioned there don't work, please provide more information about your environment, exact image versions, binding versions and a piece of code to reproduce the issue. Otherwise we need to start wondering and guessing many things.

**Comment by gokulganthtm** [comment]
@diemol Thanks for your reply ...
Sorry for the delay :( 
It works now with https://github.com/seleniumhq/selenium/issues/1158
