### ISSUE TITLE
Question about chrome and host memory

### ISSUE THREAD

**Issue by tnguyen14** [SeleniumHQ/docker-selenium#505]
Following the suggestion on the README about using the host's shared memory for Chrome:
```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.4.0-dysprosium
```

If I want to run multiple selenium tests at the same time, one way is I could spin up multiple `standalone-chrome` containers, however, this could cause problem some time, and I think it has to do with mounting the same `/dev/shm` to multiple containers?

If I was to use the hub, and then starting a new `node-chrome` each time I need to run, would the mounting of `/dev/shm` need to happen at the `hub`, or each `node` container?

What would be a recommended approach for running these multiple containers in a CI (Jenkins) environment. Should each build create their own standalone container, or should there be a long-running hub, and each build can register its own `node` container?

**Comment by diemol** [comment]
Hi @tnguyen14,

To run multiple tests in parallel, if you use standalone containers you would run into the issue of figuring out the url you need to pass establish the initial connection since each container would have a different IP. Besides that, I don't understand why you mention that it could bring problems over time.

The second approach is more suitable to run tests in parallel, the hub would handle the requests and distribute them over the nodes in the grid. The mounting of `/dev/shm` would need to be done on each `node` container.

To run it in a CI environment, try both approaches, and check what works better for you. I've met people using both scenarios and it works for them. 

Since this is not really an issue but more a question, I'd recommend you to post it on the [Selenium User Group](https://groups.google.com/forum/#!forum/selenium-users) or join the [Selenium Slack Channel](https://seleniumhq.herokuapp.com/). You will get faster feedback for questions over there.

**Comment by diemol** [comment]
I'll close this issue since it was just a question which was answered.
