### ISSUE TITLE
How may I run Selenium/hub on windowsservercore

### ISSUE THREAD

**Issue by Geekays** [SeleniumHQ/docker-selenium#515]
## Meta - Windowsservercore Docker-on-windows
Image(s):  selenium/hub

Docker-Selenium Image Version(s):  latest/any

OS:  windowsservercore (https://hub.docker.com/r/microsoft/windowsservercore/) or nanoserver (https://hub.docker.com/r/microsoft/nanoserver/)

**Comment by tparikka** [comment]
As you've noticed, our images right now all use Linux base images. They are cleaner, smaller images than you would get than the equivalent windowsservercore or nanoserver images and the toolchain for building our images is geared toward Linux as well. Is there a particular use case you have for using Windows images instead of Linux?

**Comment by smccarthy** [comment]
You can't. There are no GUI applications inside of windows containers yet.

**Comment by Geekays** [comment]
@tparikka the use cases that taking me for windowsservercore are:
1. This is .NET development
2. The test scripts are also developed in c# and Selenium
3. Other tools in the combination are on windowsservercore
4. We need to have the test run on IE as well.

I know we can have a combination of Linux and Windows and Docker and VMs (Non-Docker). But that seems to be little messy.

**Comment by tparikka** [comment]
@Geekays: As @smccarthy pointed out there are no GUI apps in the Windows containers and looking at microsoft/virtualization-documentation#214 it looks like there might be no plans by Microsoft to do this in the near future, so running IE docker images just isn't in the cards right now. That said, the OS of your Selenium containers really shouldn't matter (beyond the currently nonexistent containerized Internet Explorer). What I would suggest is writing a PS script (or other as you prefer) that uses docker-compose to instantiate your grid, drives the tests through it using NUnit (or your test framework of choice), grabs the logs and does whatever reporting off of the logs that you need. Because the docker containers are meant to be dispoable you shouldn't be running the test assemblies on them anyways, generally.

**Comment by metareven** [comment]
@tparikka There are differences between the browsers on different OSes so you might want to run your tests on the OS your customers users are most likely to use (which in most cases is windows/android/iOS). Also the webdriver for Edge only supports one instance at a time, so being able to dockerize Edge nodes would be really nice. I've also had some problems running multiple firefox instances on the same windows machine. Dockerizing the firefox hubs might alleviate such issues

**Comment by diemol** [comment]
@Geekays @metareven 

As @tparikka and @smccarthy mention, it is not possible to have EDGE nor IE in docker for now, the issue was handled [here](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214). We depend on Microsoft for this, if they don't provide a version of Windows in docker with a GUI enabled, it is not possible to have EDGE/IE in docker. Hopefully Microsoft changes their mind in the future.

On the other hand, if you want to test with Chrome and Firefox, you can run the docker-selenium containers in docker for Windows. It should work properly. 

You can also ask questions in the [Selenium Users Group](https://groups.google.com/forum/#!forum/selenium-users) or at the [Selenium Slack Channel](https://seleniumhq.herokuapp.com/).

Closing this issue as there is no action item for this.
