### ISSUE TITLE
Health check URL for the Node

### ISSUE THREAD

**Issue by vijayrcse** [SeleniumHQ/docker-selenium#517]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  

OS: 

## Expected Behavior -
Hi ,
Can anyone please let me know what would be the health check URL for a Node server( assuming i am running a node-firefox-debug )

**Comment by diemol** [comment]
Hi,

I'll answer it without knowing the context or what you want to achieve.

In general you can use something like: http://HOST:PORT/wd/hub/status

For nodes and standalone you get a JSON with a field that says something like: `status=success`. For the grid it says something like `status=13`, when it is working fine.

You just need to parse that response to check if the node is up.

Since this is not really an issue but more a question, I'd recommend you to post it on the [Selenium User Group](https://groups.google.com/forum/#!forum/selenium-users) or join the [Selenium Slack Channel](https://seleniumhq.herokuapp.com/). You will get faster feedback for questions over there.

**Comment by ddavison** [comment]
see https://github.com/SeleniumHQ/docker-selenium/issues/332#issuecomment-259264846

**Comment by vijayrcse** [comment]
this http://HOST:PORT/wd/hub/status works for the hub, but not for the node image. could you please suggest if it is same URL for node as well 

Basically i trying to configure a health check path for my node image running in AWS ECS

**Comment by ddavison** [comment]
if you noticed the subsequent comments i linked, it was grep for chrome/firefox - that's how you can check for node presence

**Comment by millerick** [comment]
@ddavison , I have a use case for this, which is running `selenium-hub` and `selenium-node` on a Kubernetes cluster.  The nodes need to expose an endpoint for readiness and liveness probes to hit in order for the cluster to properly cycle bad containers out of service and replace them with new ones.  Is there a reason why this is not supported, or am I overlooking something?  Having to probe through the `selenium-hub` process is less than ideal.

**Comment by diemol** [comment]
@millerick the url is the same one for the nodes.
