### ISSUE TITLE
Force DockerHub automated build to update chrome version

### ISSUE THREAD

**Issue by driverpt** [SeleniumHQ/docker-selenium#539]
As title says.

We want to run node-chrome with latest Chrome Version and that isn't happening because the Docker Image Automated Build isn't run for the last 2 months, causing Chrome to be stuck on 58.0.3029.81 .

If there was some kind of way to build these images daily, it would be nice as it would always have browser latest versions.

**Comment by diemol** [comment]
Hi @driverpt,

The builds are not done in the docker hub since a while ago, they are done in Travis whenever there is a release. We are keeping it that way so we can track any possible issues more easily.

We are now releasing more often, so the images are having the latest versions usually. 

Therefore, I'll close this issue since there is no need for that right now.
