### ISSUE TITLE
REMOTE_HOST is not replaceable with SE_OPTS

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/docker-selenium#540]
@McSnowflake commented on [Fri Aug 18 2017](https://github.com/SeleniumHQ/selenium/issues/4501)

## Meta
OS:  Linux using Docker
Selenium Version:  3.4.0

## Summary
The removal of REMOTE_HOST breaks usage scenarios where port mapping is needed.

## Example
Setting up a selenium grid via docker as explained here:  #432.

It's essentially this
`docker run -d --name node101 -p XXXXXX:5555 -e HUB_PORT_4444_TCP_ADDR=192.168.2.103 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 192.168.2.103 -port XXXXXX" selenium/node-chrome:3.4.0`
nodeConfig contains :   `"port": 5555`

What this is expected to do:
Multiple nodes running on one host: The nodes running at port 5555 inside containers that expose this port to be unique for the host (XXXXXX). When registering to the hub the node shall tell that exposed port to the hub instead of the internal.

What it actually does:
SE_OPTS  overwrites the nodes port setting, which will make it use this port (XXXXXX) inside the container which will break the port mapping.

## Conclusion
REMOTE_HOST allowed to tell the node the exposed port (without overwriting its port setting), so that it could then tell the hub to use it, making port mapping actually possible.

## Related tickets
 #307, #481, #432

**Comment by McSnowflake** [comment]
@barancev I created this ticket at selenium intentionally, because the REMOTE_HOST param is not special for the docker images, but was a basic selenium feature. At least that's what I understood.

**Comment by diemol** [comment]
@McSnowflake as mentioned in the linked issue, `REMOTE_HOST` was a parameter used in docker-selenium, it is now deprecated in favour of `SE_OPTS=\"-host <host> -port <port>\"`.

Could you please elaborate more your use case to understand what you need to achieve?

**Comment by diemol** [comment]
Extra comment for precision, `REMOTE_HOST` was dropped in Selenium 3, that is why you might be wondering @McSnowflake. And since it was dropped, the images moved to use `-host` and `-port`.

**Comment by diemol** [comment]
@McSnowflake, to summarise, the `REMOTE_HOST` cannot be passed as a environment variable, but it can be used via the `SE_OPTS`. Here is an example:

Start hub:
```
docker run -p 4444:4444 --name selenium-hub selenium/hub:3.7.1-beryllium
``` 

Start node:

```
docker run --name node101 -p 5595:5555 \
    -e HUB_PORT_4444_TCP_ADDR=192.168.1.7 \
    -e HUB_PORT_4444_TCP_PORT=4444 \
    -e SE_OPTS="-remoteHost http://192.168.1.7:5595" \
    selenium/node-chrome:3.7.1-beryllium
```

Like this, the hub will use the address reported in `-remoteHost` to reach the node. 

The images deprecated the use of `REMOTE_HOST` because it was used in the JSON config for the node, and based on my findings, that value is not supported in the JSON anymore, but it is supported as a flag in the command line.

Please give it a try and give us feedback based on your results. If you encounter any problems, please feel free to reopen this issue.
