### ISSUE TITLE
Selenium hub with node chrome can not load URl of locahost.

### ISSUE THREAD

**Issue by cstgyxlove** [SeleniumHQ/docker-selenium#541]
## Meta -
Image(s):  

Docker-Selenium Image Version(s):  Latest

OS:  OSX Yosemite

## Expected Behavior -
I want to use selenium to test my app. my app runs on docker and question is I will deploy it on jenkins. Since jenkins hasn't installed chrome. so I use selenium hub to do this.
The docker selenium works fine with public url, it can get element from website like google.com or github.com. But it fails when I want to get element on url like localhost:8000/the-url-of-my-app-api. Not such element error.

**Comment by Drimix20** [comment]
Isn't this a problem caused by configuration of docker containers? If you want to have application available from your localhost and port 8000 than you have to configured port mapping to specific running container where you application is deployed (`docker run -d -p 8000:8000`). Because your application must be reachable from the docker container where selenium server is running. Do you have set it correctly?

**Comment by cstgyxlove** [comment]
@Drimix20  I found the reason, it is because I didn't set one public url for my app. localhost is only for one container. I appreciated your response. Thank you.
