### ISSUE TITLE
Exit:127 Error after running container selenium/standalone-firefox-debug: 2.53.0

### ISSUE THREAD

**Issue by yuklia** [SeleniumHQ/docker-selenium#590]
## Meta -
Image(s):  
selenium/standalone-firefox-debug: 2.53.0
Docker build is failed thus there is no chance to run container. 
https://hub.docker.com/r/selenium/standalone-firefox-debug/builds/

Docker Version:  
Version 17.09.0-ce-mac35 (19611)

OS: 
macOs High Sierra

## Expected Behavior -
 Exit 0
## Actual Behavior -
there is en error during running container
 **/opt/bin/entry_point.sh          Exit 127**

**Comment by diemol** [comment]
Hi @yuklia,

If you found any issues in old images, it is very probable that they are fixed in the new ones. We improve them constantly, so please try the newest versions of the images.

In addition, we don't maintain old versions of the images, we make the needed fixes and improvements in the current versions and release again.

Please give a try with the current images and create a new issue in case a problem is found.

I'll close this issue since it refers to an old image not maintained anymore.
