### ISSUE TITLE
How to find browser version on which my test are running?

### ISSUE THREAD

**Issue by shohilbagdai** [SeleniumHQ/docker-selenium#598]
I am running my test on selenium/standalone-chrome:3.3.1 image but I don't know how to find on which Chrome version my test are running?

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by diemol** [comment]
In addition to that, there is already an issue with that information, please check #186
