### ISSUE TITLE
Firefox video playback support

### ISSUE THREAD

**Issue by ViljarVoidula** [SeleniumHQ/docker-selenium#661]
## Meta -
Image(s):  

Hub: 3.4-3.8 (does not matter)
Docker-Selenium Image Version(s):  

Firefox: 3.4-3.8 (does not matter)
Docker Version:  

17.09.0-ce
OS: 

Linux, Windows, MacOS

## Expected Behavior -
Video playback in Firefox nodes

## Actual Behavior -
Failed video playback because of missing codecs.
I recently got a project where i have to test jwplayer wrapper . In latest chrome image, video started playing as expected, however in firefox it did not. After a while debugging a understood that problem was missing codecs in firefox node. Is it possible to add ffmpeg codecs to firefox image?

> RUN apt-get update -qqy \
  && apt-get -qqy install \
  x11vnc \
  ffmpeg \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

**Comment by ddavison** [comment]
> Expected Behavior -
Video playback in Firefox nodes

Didn't know we ever had that SLA 😅 

when you are playing your videos, @ViljarVoidula - how are you validating that they are playing back?  Selenium doesn't do this natively, unless you are just checking an "autoplay" attribute

**Comment by ViljarVoidula** [comment]
@ddavison 
I have tested player front-end wrappers for a while now , depending on project I've used different methods to get player related information ( executing client-side js to alert state for example and using that to validate it , why alert, cause alert is synchronous call and stops all other clientside JS so i can trust that it outputs always correct value from player - hacky, but its not stupid if it works) .

**Comment by testphreak** [comment]
I have run into the issue as well, trying to check playback state using JS for a mp4 video in Firefox running inside a container. Works on Firefox/Mac. Would be awesome if we could install the necessary codecs.

**Comment by diemol** [comment]
Well, I am not sure how to proceed here, because installing ffmpeg in the images just opens the door to enabling video recording, and that is another layer of complexity that I am not sure if we want to support for now. We try to keep the images as generic as possible and I don't know how common this use case is :)

In addition, the image size would increase and I'm not so sure about doing that...

My suggestion for now would be to use `elgalu/selenium` image, which already contains the packages you need.

What do you think?

**Comment by ViljarVoidula** [comment]
@diemol - it does not have to be ffmpeg to enable video playback option ( recording is not in scope, just playback) . I just used ffmpeg cause i knew it's enabled by default if present in system . I found a mozilla bug from past https://bugzilla.mozilla.org/show_bug.cgi?id=1207429 . Maybe there's smaller packages aswell.
At the moment it's kinda awkward that chrome nodes have codecs enabled, and video playback is possible, and firefox does not. 

_elgalu/selenium_ is great - tested and it works .

In the end i think it's up to you , i understand your point and adding a extra complexity is always adding an extra package to check and maintain. Perhaps a small note somewhere in Readme that official HQ image does not support video playback within FF container and reference to elgalu , similar to http://www.seleniumhq.org/download/ and not developed by seleniumhq section ? 

Whatever you choose - I respect your decision .

**Comment by diemol** [comment]
@ViljarVoidula, sorry for coming back so late to this issue.

We really prefer to keep it out of the images, for example we added a package for (perhaps) a similar purpose, see #614... And it seems this broke in FF 58, but we cannot do anything about it plus we need to maintain it. Additionally, no one reported the issue since it seems no one is using it.

That is why we encourage users to extend these images and make them fit their needs for their use cases. Therefore, the more things we add, potentially we could break use cases created by extending these images.

I think your suggestion is a good idea, perhaps adding a small notes section at the end with those type of comments is helpful. If you feel like adding it, we could happily receive a PR for that.

Again, sorry for the long wait, and we hope you understand. 

Closing the issue...
