### ISSUE TITLE
Setting the PAC script and credentials in Chrome and Firefox

### ISSUE THREAD

**Issue by ReneHerrero** [SeleniumHQ/docker-selenium#678]
Hi,
Anyone know how to set the PAC script and credentials in Chrome and Firefox?
I'm thinking that creating new images derived from the node-chrome and node-firefox would make everything work in our corporate environment?
Thanks

**Comment by diemol** [comment]
Hi @ReneHerrero,

Yes, that should be possible because in the end it is just about placing the file in the right place, either by mounting a volume or creating a new image based on these ones.

Since this is more a question rather than an issue, please send it to the [Selenium User Group](https://groups.google.com/forum/#!forum/selenium-users).
