### ISSUE TITLE
support plugins for the server container

### ISSUE THREAD

**Issue by travisghansen** [SeleniumHQ/docker-selenium#683]
I see loading selendroid and ios-driver require special instructions/needs for loading the grid.  Would it be possible to allow plugins of this nature to be mounted into the container and proper arguments applied without building a custom startup script/container?

Thanks!

**Comment by diemol** [comment]
Hi @travisghansen,

Not really, the idea of the images is to provide a general tool that people can use and extend to suit their needs. In this case, it would be an specific use case, that perhaps fits some users but certainly not all of them. This add-ons make the images heavier and harder to maintain (in this case plugins need to be updated and tested properly before releasing).

If feel like giving ir a try, I recommend to take these images as base and then build up on them, you can check this Wiki for further instructions https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images.

I'll close this issue since there is not an action item for us to work on.
