### ISSUE TITLE
Segmentation fault of selenium/hub on MacOS

### ISSUE THREAD

**Issue by MrTheodor** [SeleniumHQ/docker-selenium#686]
## Meta -
Image(s):  selenium/hub

Docker-Selenium Image Version(s):  3.10.0-argon

Docker Version:  17.12.0-ce

OS: OSX 10.13.3

## Expected Behavior -

```bash
$ docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.10.0-argon
```
container runs properly

## Actual Behavior -

```bash
$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS               NAMES
e196620ca1cc        selenium/hub:3.10.0-argon   "/opt/bin/entry_poin…"   3 minutes ago       Exited (139) 3 minutes ago                       selenium-hub
```

I run bash in the container and `java` command which results with the segmentation fault error code 139.

I have reinstalled openjdk inside the container and that helped.

**Comment by diemol** [comment]
Hi @MrTheodor,

We are installing openjdk-8-jre-headless in the image, which does not have support for GUI Java apps, that could be the reason why you saw that error. In addition, the idea of the images is to provide a general tool that people can use and extend to suit their needs. If you want to spin more processes inside the container, I recommend to take these images as base and then build up on them, you can check this Wiki for further instructions https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images

I'll close this issue since there is not an action item for us to work on.
