### ISSUE TITLE
Connecting a chrome/firefox-node in a docker container (win 7) to the seleniumgrid on the local network

### ISSUE THREAD

**Issue by ankitrathi85** [SeleniumHQ/docker-selenium#709]
I am unable to connect a win 7 docker selenium grid node (firefox or chrome ) to a local network hub.

This is the sample docker-compose I am using 

version: '2'
services:
  firefox:
    restart: always
    image: selenium/node-firefox-debug 
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: 10.0.0.3
      HUB_PORT: 4444
      version: automation-server

    
I already have a grid up and running using regular selenium server files 
![image](https://user-images.githubusercontent.com/7059774/37766690-b81d1c22-2ded-11e8-81b2-7288da499164.png)

the docker node is able to reach the hub but looks like vise versa is not true.  I am also unable to manually ping the docker node IP coming up in grid.

I am able to ping the VM IP though which is different (192.168.99.100)

What other configuration is needed in a set up like this? Is this due to win 7 that a local hub is unable to get to a container node in virtual box VM?

**Comment by diemol** [comment]
Hi @ankitrathi85,

As you can see in the image, the node reports itself with the internal IP that it has in the docker VM (176.18.0.2). But the IP, as you mention, that should be used to access the node is 192.168.99.100.

When having this non-typical configurations, it is necessary to tell the hub where to find the node as well. For that, please check the section https://github.com/SeleniumHQ/docker-selenium#selenium-hub-and-node-configuration-options, where the `remoteHost` option is explained.

I'll close this one since this was a question rather than an issue. For questions, you can post them in the [Selenium Google Group](https://groups.google.com/forum/#!forum/selenium-users) and also join the community chat on [IRC/Slack](https://seleniumhq.herokuapp.com).
