### ISSUE TITLE
How to use docker without 'sudo' if docker was run with 'sudo'

### ISSUE THREAD

**Issue by Larry19b** [SeleniumHQ/docker-selenium#714]
## Meta -
Image(s): standalone-chrome
Docker-Selenium Image Version(s): 3.7.1-beryllium
Docker Version: 17.12.0-ce
OS: Mac OS X

## Description
When I do a docker run command using sudo:
sudo docker run...

It seems I have to use 'sudo' for every subsequent command
Is there a way I can access the docker without using 'sudo' in this case

Because anytime I run:
docker ps -a | [containerId]

the docker can't be found unless I add 'sudo' to the command

**Comment by dylanlive** [comment]
@Larry19b I suggest you read through https://docs.docker.com/install/linux/linux-postinstall/

Creating a docker group and adding your user will allow you to run docker commands without sudo.

**Comment by Larry19b** [comment]
@dylanlive thanks for the advise. I did go through it and successfully added the group but when I wanted to add my user (i.e. the mac user) to the group, using
sudo usermod -aG docker $USER

I got this:
usermod: user '[myUsername]' does not exist

**Comment by diemol** [comment]
Hi @Larry19b,

You mention that you are running docker on a Mac OSX, and somehow you need to execute every docker command with `sudo`. This seems like a misconfiguration in your mac, the first result from Google points to https://stackoverflow.com/questions/40325352/why-am-i-forced-to-run-docker-with-sudo-on-os-x.

Besides helping a bit with the link above, there is not much in our area that we can do. I'll close this issue since there is no action for us here.
