### ISSUE TITLE
Customized Image problems with entrypoint. have i done it wrong?

### ISSUE THREAD

**Issue by Shinoby1992** [SeleniumHQ/docker-selenium#715]
## Meta -
Image(s):  
using a standalone debug image created locally with Make
Docker-Selenium Image Version(s):  
latest
Docker Version:  
latest
OS: 
OSX

## What i have done -
- git clone this project
- go to base image
- edit the dockerfile
- add some install lines for python and requirements for my python script
- go to standalone folder 
- edit the dockerfile:
- add my script which is in the standalone folder to the docker image
```
COPY pythonscript.py /opt/bin/pythonscript.py
```

##Whats definitely wrong##
adding this line:
`CMD [ "python", "-u", "pythonscript.py" ]`
to dockerfile.txt in standalone folder
then running the script with 
`docker run -d -p 4445:4444 -p 5600:5900 selenium/standalone-firefox-debug:local`
ends in that my script does start, but it does not do the entry_point.sh because i cannot connect to the vnc!! 

## Expected Behavior -
running a customized standalone debug version of firefox or chrome which runs a python script after 
docker run and is available via vnc
## Actual Behavior -
does not work

**Comment by diemol** [comment]
Hi @Shinoby1992,

What is happening with that approach is that `CMD [ "python", "-u", "pythonscript.py" ]` is replacing `entry_point.sh`, so it never gets executed.

One approach would be to edit the `entry_point.sh` and invoke the Python script at the end of it (but making sure that Selenium has started properly).

Since this is more a question than an issue, I'll go ahead and close it since there is no action for us here.

For questions, you can you can post them in the [Selenium Google Group](https://groups.google.com/forum/#!forum/selenium-users) and also join the community chat on [IRC/Slack](https://seleniumhq.herokuapp.com).
