### ISSUE TITLE
Selenium-chrome-standalone page crash, no useful logging

### ISSUE THREAD

**Issue by uuf6429** [SeleniumHQ/docker-selenium#815]
## 🐛 Bug Report

Crashes when navigating to WordPress themes page. Further information can [be found here](https://gitlab.com/gitlab-com/support-forum/issues/4047) (cross-posted since I'm not sure who can best answer/investigate and the answer might help someone in the future).

Reproducible sample repo on gitlab: [uuf6429/selenium-wp-chrome-crash](https://gitlab.com/uuf6429/selenium-wp-chrome-crash/)

Interestingly, everything works when run without `gitlab-runner`, suggesting the issue might be related to it.

## To Reproduce

- tell chrome to navigate to `/wp-admin/themes.php?theme=serena`
- any further steps will yield a "page crash"

## Expected behavior

No crash or at least a better indication of when and why. Even with full debug logging, the only indication of the crash is from a response message.

## Test script reproducing this issue (when applicable)

See the repo linked above. Apologies in advance if it looks complicated - there's a lot of glue work. In practice one can ignore stuff inside `/bin`, `/vendor` and `/features/bootstrap`.

## Environment

OS: Windows 10, CoreOS
Docker-Selenium image version: `selenium/standalone-chrome:latest` (`3.14`)
Docker image ID: `dab53d6faaf1`

Docker version: `Docker version 18.03.0-ce, build 0520e24302`
Docker-Compose version: `docker-compose version 1.20.1, build 5d8c71b2`

**Comment by diemol** [comment]
Hi @uuf6429,

I checked the docker-compose file placed in the Git repo linked above, and it is missing the `/dev/shm` / `--shm-size=` [part](https://github.com/SeleniumHQ/docker-selenium#running-the-images), which is something that I don't really know how to do in the `gitlab-runner`, I believe there is an issue created in the repo/issue tracker. (That's why it works without it).

Please check their docs and forums to see if there is a way to configure that part. It is not really a docker-selenium issue.

**Comment by uuf6429** [comment]
Hello @diemol,

I'm not sure I fully get what you spoke about, [/dev/shm is shared](https://gitlab.com/uuf6429/selenium-wp-chrome-crash/blob/master/docker-compose.yml#L15) and with the correct size (from my testing).

But with that apart, my main concern with regards to docker-selenium is why nothing shows up in logs. This part cannot be possibly solved by GitLab.

**Comment by diemol** [comment]
You are right, somehow I saw it but I missed that. Let me run that docker-compose file and report back.

**Comment by uuf6429** [comment]
Thanks!

**Comment by diemol** [comment]
Things work locally fine, are you sure that the volume really gets mounted?
What is the output of the log for the `selenium_1` container?
Can you take a screenshot when your test fails?

**Comment by diemol** [comment]
Sorry, I don't use `gitlab-runner`.

I think the log is pretty clear:

```
selenium_1   | 2018-10-20T20:18:01.050108016Z 20:18:01.045 DEBUG [Passthrough.handle] - To downstream: {"sessionId":"ef2e0d544c1e7df56212cc6311e880f0","status":13,"value":{"message":"unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.14.48-coreos-r2 x86_64)"}}
```
Which is the same issue as #589,  #431, #636, https://bugs.chromium.org/p/chromedriver/issues/detail?id=2283. 

A browser screenshot would just show the crashed tab, (you can always take a screenshot on test failure, the session is closed by the test framework, not by Selenium).

I am not sure how to proceed, since the error shows the issue with the `shm` memory.

PS: 
Seems you cannot mount volumes there https://gitlab.com/gitlab-org/gitlab-runner/issues/1234, but I might be wrong.
Looks like you need to set `--shm_size` https://gitlab.com/gitlab-org/gitlab-runner/issues/1913 https://docs.gitlab.com/runner/configuration/advanced-configuration.html

**Comment by uuf6429** [comment]
Thanks for the investigation!

Regarding the GitLab aspect, let's hope they might be able to clarify a few things. I'm still new at playing `gitlab-runner`, but whatever ails me seems to happen on their side too. Or it could just be due to their 2gb instances (can't be sure because failures still happened on my 4gb local machine).

So basically, the only indication of a failure is a DEBUG message of a response? Isn't there any other selenium/chromedriver logging that would show more details, maybe a trace or so?

**Comment by diemol** [comment]
For Chrome not so much, a change in the configuration would be needed to see that output, if you want to help us a PR would be appreciated :) 
But the message provided by the debug log is enough in this case, it is a known message when running Chrome in containers.

**Comment by diemol** [comment]
Cool, thanks for the desire to contribute! You could have a look on how Firefox does it, in theory it should be something similar to [this](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeFirefox/generate_config). 
Best way is to try it locally with the plan Java jar and when it is working, then just add it to the containers.

If you have any questions, feel free to join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where we can build more on it.

Going back to the initial issue, I think there is not much to do here, (besides the potential PR, that would be handled in a separate place). I would say this issue can be closed since it is more related to the GitLab runner. What do you say?

**Comment by uuf6429** [comment]
Agreed.
