### ISSUE TITLE
[Question] What is the minimum recommended ram to run needed to run this containers?

### ISSUE THREAD

**Issue by frosty00** [SeleniumHQ/docker-selenium#823]
For some reason firefox and chrome keep crashing on my 1 gb of ram vps. What is the recommended amount of ram needed to run these containers, I saw the 2gb as the -shm option and was not sure if that was refering to ram.

**Comment by diemol** [comment]
Hi @frosty00,

The rule of thumb is 1GB and 1 CPU per browser, this might vary on the application under test. Take into account to leave some RAM and CPU for the normal operating system processes. 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
