### ISSUE TITLE
Docker Session Not Killed Automatically + TIMEOUT Issue

### ISSUE THREAD

**Issue by vinoopraj** [SeleniumHQ/docker-selenium#853]
Hi Team,

When we set GRID_TIMEOUT: 0, there is no session timeout issue and things work well in version 3.141.59-copernicium. But when the jenkins job is aborted, the grid session is not coming back after long while. When i change the GRID_TIMEOUT :30, the session is coming back automatically after 30 seconds. But could not executed more jobs and most of them are skipped due to timeout issue, if the GRID_TIMEOUT:0. Suggest  a better way to deal with this.  Even tried with GRID_BROWSER_TIMEOUT and GRID_NEW_SESSION_WAIT_TIMEOUT, this does not helped. 

Thanks in advance
Vinoop

**Comment by diemol** [comment]
Hi @vinoopraj,

It just seems that the job preparation and teardown in Jenkins are not preparing or leaving a clean environment.

Moreover, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by vinoopraj** [comment]
Thank you Diego
