### ISSUE TITLE
Passing custom servlets to node in docker-compose.yml.

### ISSUE THREAD

**Issue by quldude** [SeleniumHQ/docker-selenium#856]
I'm trying to pass in custom servlets to the node using the following environment variable:
```
- SE_OPTS=-cp selenium-extras.jar -servlets com.node.servlets.FileServlet,com.node.servlets.ExecuteServlet,com.node.servlets.MouseServlet -maxSession 1
```

"selenium-extras.jar" contains my custom servlets code. I'm using the selenium/node-chrome-debug image.

But not having luck. I get this error:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-cp' but no main parameter was defined in your arg class
```

What am I doing wrong?

**Comment by diemol** [comment]
Hi @quldude,

It won't work because the `SE_OPTS` is made to pass Grid options, not to pass a command like the one you want to pass.

You would need to create your own image, by adding the custom jar to it and customising the command to start the node https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/start-selenium-node.sh#L39

Moreover, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
