### ISSUE TITLE
Problem with `ENV HOME`

### ISSUE THREAD

**Issue by stephennyu** [SeleniumHQ/docker-selenium#895]
Hi,

Wondering why `HOME` variable is hardcoded here as it causes some issue when installing packages(e.g. python packages) that makes the packages being attempted to be installed on this directory instead

One workaround that I'm currently doing right now is I change the user and HOME directory back before installing the packages
```
USER root
ENV HOME "/root"
```

Do we need this ? Is there any other way ?

Thanks

**Comment by diemol** [comment]
@stephennyu it is done like that because the project is structured that way, the purpose of it is having Grid and browsers configured and running in a simple way. 
I assume you are extending the images, therefore you can change them in any way it works better for you. 

This is not really an issue, so I'll close it.
