### ISSUE TITLE
Selenium node chrome debug with multiple VNC ports in docker compose file

### ISSUE THREAD

**Issue by jibinjose087** [SeleniumHQ/docker-selenium#896]
The below configuration in docker-compose file with a replica of 5 will create five containers with same VNC port and different internal IP or hostname. If we did the same thing on an ec2 machine then how we access those VNC desktops via public IP? 

====
  chrome_node1:
    image: selenium/node-chrome-debug:3.141.59-gold
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - test
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5557" /opt/bin/entry_point.sh'
    ports:
      - "5557:5900"
    deploy:
      replicas: 5
========

Adding the same entry multiple times in docker-compose file with different IP will do the trick but I am looking for any other alternative solution.

**Comment by diemol** [comment]
@jibinjose087 
This is not really a docker-selenium question, it is more related to docker-compose. 
In addition, this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.


PS: Check also the docker documentation, a quick search in Google brought me this: https://docs.docker.com/v17.09/compose/compose-file/compose-file-v2/#ports.
