### ISSUE TITLE
port already allocated

### ISSUE THREAD

**Issue by daleyc02** [SeleniumHQ/docker-selenium#906]
when i run docker 
"docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug"

I get the Below error.How do i fix this.

docker: Error response from daemon: driver failed programming external connectivity on endpoint happy_feynman (05e214513296cb1491e9a1a0a80b7177bbda00c94f09081af781f78d49cde266): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
