### ISSUE TITLE
Firefox ESR Container Image

### ISSUE THREAD

**Issue by dpsi** [SeleniumHQ/docker-selenium#907]
## 🚀 Feature Proposal

[Selenium supports the latest and previous ESR releases of Firefox
](https://www.seleniumhq.org/about/platforms.jsp). I would like to see containers for these releases to be built as well.

## Motivation

Selenium already supports it so it should (in theory) be simply a matter of getting the images built by the CI. 

As browsers have adopted rapid release schedules to stay on the bleeding edge of web technology and to combat security vulnerabilities, many enterprises are not prepared or do not have the resources to validate the rapid releases. ESR releases are kept up to date security wise while maintaining a stable API and sandbox for enterprises and legacy websites. As the popularity of ESR increases, developers need an easy and convenient way to verify functionality on these versions.

**Comment by ddavison** [comment]
i could be wrong, but i believe you already can do this.

see [buildling your own images](https://github.com/SeleniumHQ/docker-selenium/wiki/Building-your-own-images#specify-firefox-version).  by specifying the Firefox version of ESR, you can go home free

**Comment by diemol** [comment]
Exactly, it should possible to build it already with the link that @ddavison mentions above. Please give it a try and let us know how it goes.

Closing as this is already an existing feature.

**Comment by dpsi** [comment]
Hello,
I am well aware of manually building the images. The only reason I bring it up here is so that the containers could also be built by CI along with the other containers. I am sure other developers are interested in using these ESR images if given the opportunity. The selenium system of nodes allows us to simply drop in a different node type which is great for developers.

My company requires us to work in an air-gapped network that allows us to pull from the docker hub, but not from anywhere else such as the apt repos, mozilla's servers for FF binaries, and github for gecko-webdriver. Bringing in these artifacts into the air-gap is tedious, and not automatable. 

It's not a very big issue, just an improvement in UX. In the meantime we'll just not test against ESR, as building our own images defeats the purpose of using selenium docker in the first place (in our use case that is).

Thanks for the consideration,
Darien

**Comment by ddavison** [comment]
it's a difficult position @dpsi .  if we keep growing the amount of images from our end, that's just that many more containers that we have to maintain.

by limiting the number of containers and keeping those containers configurable and generic - it lightens the load on us since we are only two maintainers at the moment.

> I am sure other developers are interested in using these ESR images if given the opportunity

believe me - there are many people that request a lot of additional functionality (video recordings, etc) but there are things that we aren't settling for for the reason i had lain out above. we are keeping these images small.  and the small images we have out there, we want to keep them more configurable, instead of having

selenium-node-firefox-esr
selenium-node-firefox-nightly
selenium-node-firefox-stable.

see we could do this easily in CI, but the maintenance becomes a nightmare maintaining all these separate images and one-offs that we'd have to implement in one image, but not the next.

hopefully this explains a little bit our side and opened your mind a bit to why we most likely won't be putting it in.
