### ISSUE TITLE
Unable to reach the node from hub 

### ISSUE THREAD

**Issue by barri-krishna** [SeleniumHQ/docker-selenium#914]
Unable to reach the node (installed in a docker container) from the hub (installed in the local machine). Tried with REMOTE_HOST but didn't work.

**Comment by diemol** [comment]
We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. Closing this issue for now, please fill a new one with the complete template filled out.
