### ISSUE TITLE
Calling window.setSize fails with unknown command: session/<session_id>/window/size in 3.141.59-palladium

### ISSUE THREAD

**Issue by johnbindel** [SeleniumHQ/docker-selenium#918]
## 💥 Regression Report

Running ```browser.manage().window().setSize(1366, 768);``` call fails and produces this error:

```unknown command: unknown command: session/<session_id>/window/size```

## Last working version

Worked up to version: 3.141.59-oxygen

Stopped working in version: 3.141.59-palladium

## To Reproduce

Run a protractor script that sets window size with ```window.setSize(width, height);```

## Expected behavior

Successfully resize window as it previously did.

## Environment

OS: Ubuntu 18.04
Docker-Selenium image version:
selenium/hub:3.141.59-palladium
selenium/node-chrome:3.141.59-palladium
-->
Docker version: 18.06.1-ce
Docker-Compose version (if applicable): 1.22.0, build f46880fe

**Comment by diemol** [comment]
@johnbindel 

From ChromeDriver & Chrome 75 and up, it will default to W3C mode, see release notes:
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

The command:
`session/<session_id>/window/size` is not [W3C compliant](https://www.w3.org/TR/webdriver1/#commands), this is something that needs to be fixed in Protractor (or perhaps it works in the latest version).

It means that all commands must be W3C complaint, if you still need time to update your test scripts, you can pass `w3c: false` inside the `goog:chromeOptions` block. Take into account that the flag will probably be removed in future ChromeDriver releases.
