### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by d3pr3553d** [SeleniumHQ/docker-selenium#931]
Connection refused from Selenium Grid Hub.
 Using OSX Mojave 

I have utilized the following to narrow down the IP address
localhost:4444 
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id

The result is either the hub refuses to connect or that the connection times out.

I've yet to find a workaround to reach the Selenium Hub.

**Comment by diemol** [comment]
We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template by creating a new issue.

If this is a question, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by d3pr3553d** [comment]
So you close the issue without attempting to address the bug that you seem to know clearly about? What exactly is the issue with the information that I provided? What about the template would've provided value to the developers to fix the issue? I added exactly what I would need to fix a issue in production without adding unnecessary logs and configuration screenshots that nobody else will care about and that you cannot replicate.

The meat and potatoes are:
My system is OSX Majave

The issue:
When one pulls and run the selenium/hub:latest, they will not be able to connect via the ways listed above. This is an availability issue and most application developers would consider it a SEVERITY 1 issue.

Yes, one can download the jar file and run it and achieve the expected results however this isn't the desired outcome since we are trying to develop with Selenium Framework  in a container to allow distributed testing and faster responses to hot fixes.

**Comment by diemol** [comment]
I am sorry @d3pr3553d if closing the issue right away comes as something rude, the thing is that we have created issue templates that help us to recreate the issues and therefore find a way to fix them.

And you are telling me:
>the bug that you seem to know clearly about
But honestly I don't know about it. Please just take the time to give us enough information.

In this case, we are missing the instructions on how you are starting the containers, what test script are you using to bump into the issue. Personally, I cannot really figure out what the issue could be without all the information we request in the template.

**Comment by dylanlive** [comment]
I agree with diemol. I've read through and my understanding of your report:
With macOS Mojave, you're unable to launch a Selenium Grid Hub docker container.

I have been able to launch the container on macOS Mojave, using:
`docker run -p 4444:4444 selenium/hub:3.141.59-palladium`

So to echo the above, we need more detail around how you're launching the container. Feel free to reach out to me via the IRC/Slack Channel.
