### ISSUE TITLE
Any update on Docker Images for IE/Edge

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/docker-selenium#936]
Hi All,

Are there plans for providing Docker images for running WebDriver tests against IE/Edge browser similar to what we have currently for Chrome and Firefox?

I have installed docker in windows 10 OS and I'm running selenium tests on Chrom-debug and Firefox-debug containers.

Is there any way to run selenium tests on IE/Edge in containers?

I have seen few posts like create VirtualBox inside the container and running IE/Edge tests, How to do this?

Many issues here closed with no updates :(
https://github.com/SeleniumHQ/docker-selenium/issues/350
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214

Is there any update on this issue,

TIA

**Comment by hazmeister** [comment]
Since work started to move Edge to a fork of Chromium, Microsoft has [hinted](https://www.reddit.com/r/IAmA/comments/c094uf/hi_reddit_were_the_team_behind_microsoft_edge_and/er7qiao/?context=3) that a linux build would be possible, although they have yet to commit to producing it yet. Linux support would allow a cross platform docker image.  Come back if a linux build ever surfaces.

If you fancy getting your hands dirty, there is [another option](https://medium.com/@aandryashin/selenium-on-windows-docker-revolution-f5a7eab205ad).

**Comment by diemol** [comment]
Thanks @hazmeister for replying, that is exactly what I had in mind. 

Closing as this is not an issue.
