### ISSUE TITLE
Question: docker compose healthcheck

### ISSUE THREAD

**Issue by nealio42** [SeleniumHQ/docker-selenium#937]
hi, how do I do a healthcheck within version 3 of docker compose file? can you please provide example?

**Comment by diemol** [comment]
Hi @nealio42,

A simple Google search brings up https://docs.docker.com/compose/compose-file/

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
