### ISSUE TITLE
Hi I want to use this docker image to run my tests in bamboo. For this, what should I provide in the docker image field as shown in screenshot. Thanks in advance.

### ISSUE THREAD

**Issue by ramesh5819** [SeleniumHQ/docker-selenium#940]
![Capture](https://user-images.githubusercontent.com/9509293/60581148-67b72d00-9dda-11e9-83af-76e288285265.PNG)
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
