### ISSUE TITLE
Docker-selenium not working using docker-client (java) on centos or ubuntu

### ISSUE THREAD

**Issue by ahafid01** [SeleniumHQ/docker-selenium#944]
When I use [Docker-client](https://github.com/spotify/docker-client) to create container and run test on Docker-selenium image on aws (ec2, centos or ubuntu), I have this error : unknown error: unable to discover open pages.

But my tests working fine on my mac, also its working fine if I use command line to create container and run tests on aws.

Versions :
docker-client : 8.16.0
selenium-java : 3.141.59
selenium/standalone-chrome : 3.141.59

Thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by ahafid01** [comment]
Thank you diemol
