### ISSUE TITLE
mobileEmulationEnabled is always undefined from 3.141.59-palladium

### ISSUE THREAD

**Issue by aha-oretama** [SeleniumHQ/docker-selenium#950]
## 🐛 Bug Report

From 3.141.59-palladium, `mobileEmulationEnabled` in Capabilites is undifined even though `goog:chromeOptions`'s `mobileEmulation` is set.

## To Reproduce

I create a minimum project for reproducing by using `webdriverio`.
https://github.com/aha-oretama/selenium-docker-reproduction

If you run `3.141.59-oxygen` image by following command, the test command `npm run test` will result in a success.
```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-oxygen
```

However, if you run `3.141.59-palladium` image, the test will fail. 
```
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-palladium
```

If you do not run any docker image and you've already install chrome locally, the test runs in local chrome and will succeed.

## Expected behavior

 `mobileEmulationEnabled` in Capabilites should be true if `goog:chromeOptions`'s `mobileEmulation` is set.

## Test script reproducing this issue (when applicable)

See `To Reproduce`

## Environment

OS: macOs Mojava
Docker-Selenium image version: above standalone-chrome:3.141.59-palladium
Docker version: Docker version 18.09.2

**Comment by diemol** [comment]
Hi @aha-oretama,

Thank you for providing a reproduction script. Nevertheless, this issue is not caused by `docker-selenium`, and probably not by `WebDriverIO` either. Chrome 75 and above work in W3C mode by default and this means that the returned payload when a session is created is different. Please check with the Chromium team if this is indeed an issue on their side, at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by aha-oretama** [comment]
Thank you for your explanation. I got it!
