### ISSUE TITLE
Problem when switching from standalone to hub/node with Firefox

### ISSUE THREAD

**Issue by Tchoupinax** [SeleniumHQ/docker-selenium#962]
Hello,

I have a strange problem with Selenium. When i use Firefox standalone docker, it works well as expected. However, when i use the selenium grid (hub docker) and the Firefox node, i have this error : `Error while running .getAllWindowHandles() protocol action: GET /session/88612c34-2cef-47fa-9d3d-f14f003a8376/window_handles did not match a known command`. This error comes from Nigthwatch.js, the test framework i use to pilot selenium. i DO NOT have this error with Chrome with Standalone docker and HUB/NODE Chrome docker. Both work. Only with Firefox.

According to Dockerfile, standalone Firefox image is just the Firefox node image with one more copy of the script starting Selenium. I don’t see others differences so i don’t understand where can be the difference.

Someone has an idea ? 

Thank you in advance.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
