### ISSUE TITLE
How to disable CORS or set Access-Control-Allow-Origin in header when start a grid hub

### ISSUE THREAD

**Issue by zcmgyu** [SeleniumHQ/docker-selenium#963]
## 💬 Questions
When I call Selenium Hub from browser, it doesn't allow client connect to server because of CORS policy.
> Access to fetch at 'http://localhost:4444/wd/hub/session' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

So, how to disable CORS or set Access-Control-Allow-Origin when I start a Grid hub or Docker-Selenium-Hub through parameter?
Thanks a lot (bow)

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by zcmgyu** [comment]
https://github.com/SeleniumHQ/selenium/pull/7540

I made a PR for this issue.
