### ISSUE TITLE
How to execute automation scripts  in Windows environment

### ISSUE THREAD

**Issue by pallavkrishna** [SeleniumHQ/docker-selenium#968]
## 🐛 Bug Report
Hi ,
using docker version (18.06.0-ce) , used image docker pull selenium/standalone-chrome need to execute scripts in windows environment but it executes scripts in linux environment .
please help how to download image and execute in windows environment.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
