### ISSUE TITLE
Is it possible to disable ssl check of standalone-chrome

### ISSUE THREAD

**Issue by noobcoderT** [SeleniumHQ/docker-selenium#972]
I am now using standalone-chrome in docker container to do some tests. My container network is IPv6 only, and when I opened an https website, it failed to check ssl. So I'm wonder if it is possible to disable ssl check of chrome?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
