### ISSUE TITLE
Unable to install packages when creating Selenium base image 

### ISSUE THREAD

**Issue by shmikkil** [SeleniumHQ/docker-selenium#981]
## 💬 Questions and Help

Trying to build a Selenium base image with Ubuntu 16.04 but unable to install the packages along with the path from where the Ubuntu should be pulled from...Appreciate your help!
![SeleniumBase_DockerfileIssue](https://user-images.githubusercontent.com/17186637/68156473-e7384280-ff19-11e9-8548-53111f5f4440.png)

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by shmikkil** [comment]
Thank You! Will do...
