### ISSUE TITLE
Need to run on particular node

### ISSUE THREAD

**Issue by qburst-hari** [SeleniumHQ/docker-selenium#988]
## 🐛 Bug Report

Consider like I have 3 docker images of node-chrome-debug. I need to run on a particular instance. How can I configure that. There is an option to set applicationName in the node. But do we have that as a parameter for the container.

Please help

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or check https://selenium.dev/support/ for more ways to get in touch, then the community can help you as well.
