### ISSUE TITLE
Proxy is ignored for localhost/127.0.0.1

### ISSUE THREAD

**Issue by Hiteshkumars** [SeleniumHQ/docker-selenium#999]
## 🐛 Bug Report

I have upgraded docker selenium version to 3.141.59-zinc (from 3.141.59-europium), it started failing the acceptance test due to header ("user" with its value is not found in request). If I change image from zinc to europium - all works fine.

**with 3.141.59-europium:**
**Remote address of request printed at server side:**  _127.0.0.1_
**Headers:** {accept-language=en-US,en;q=0.9, host=localhost:39868, upgrade-insecure-requests=1, **user=123456789**, accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36, 
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8, via=1.1 browsermobproxy}

**With 3.141.59-zinc :**
**Remote address of request printed at server side:** _0:0:0:0:0:0:0:1_
**Headers:** {sec-fetch-mode=navigate, sec-fetch-site=none, accept-language=en-US,en;q=0.9, host=localhost:42365, upgrade-insecure-requests=1, connection=keep-alive, sec-fetch-user=?1, accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36, accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9}

## To Reproduce
Create Proxy object with host and port and set Http Proxy.

Set proxy in webdriver capabilities.

DesiredCapabilities cap = DesiredCapabilities.chrome();
cap.setCapability(CapabilityType.PROXY, proxy);

Set Proxy header
proxyServer.addHeader("user", "123456789");

Access application 
driver.get("http://localhost:8080")

Check for proxy header "user", it should be 123456789

## Expected behaviour

I am setting header with **user=123456789**, which is not getting passed by webdriver 3.141.59-zinc. If I manually call url using URLConnection with proxy - Its working (So no issue in browsermobproxy ).

And also If I use ip address instead of localhost, acceptance test working fine (proxy header available in request at server). So I guess, its ignoring proxy for localhost in the new version of webdriver 3.141.59-zinc

## Environment

OS: Oracle Linux Server release 7.5
Docker-Selenium image version: 3.141.59-zinc 
Docker version: 17.06.2-ol

**Comment by diemol** [comment]
@Hiteshkumars there are several changes between images, new browser versions, new browser driver versions and so on.
Docker-Selenium just wraps the Selenium Grid, Firefox, and Chrome, nothing more. If there is something not working right now after the upgrade, it is probably a change on those underlying components.

It is hard to diagnose this issue since we do not know what images you are using, how the containers are being started, what Selenium version you are using on the client-side...

I would advise you to double-check the browser versions being used and then pin down where the issue started happening.

I will close this issue for now since it needs more troubleshooting before identifying if it actually a docker-selenium or a selenium issue or not. If you want to, you can post the current state of the issue to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium) and perhaps the community can guide you to pin down the problem or you can also join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well.
